// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: best_selling_products.proto

package reduced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BestSellingProducts struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	YearMonthCreatedAt string                 `protobuf:"bytes,1,opt,name=year_month_created_at,json=yearMonthCreatedAt,proto3" json:"year_month_created_at,omitempty"`
	ItemId             int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	SellingsQty        int64                  `protobuf:"varint,3,opt,name=sellings_qty,json=sellingsQty,proto3" json:"sellings_qty,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BestSellingProducts) Reset() {
	*x = BestSellingProducts{}
	mi := &file_best_selling_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestSellingProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestSellingProducts) ProtoMessage() {}

func (x *BestSellingProducts) ProtoReflect() protoreflect.Message {
	mi := &file_best_selling_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestSellingProducts.ProtoReflect.Descriptor instead.
func (*BestSellingProducts) Descriptor() ([]byte, []int) {
	return file_best_selling_products_proto_rawDescGZIP(), []int{0}
}

func (x *BestSellingProducts) GetYearMonthCreatedAt() string {
	if x != nil {
		return x.YearMonthCreatedAt
	}
	return ""
}

func (x *BestSellingProducts) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *BestSellingProducts) GetSellingsQty() int64 {
	if x != nil {
		return x.SellingsQty
	}
	return 0
}

type BestSellingProductsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*BestSellingProducts `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BestSellingProductsBatch) Reset() {
	*x = BestSellingProductsBatch{}
	mi := &file_best_selling_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BestSellingProductsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BestSellingProductsBatch) ProtoMessage() {}

func (x *BestSellingProductsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_best_selling_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BestSellingProductsBatch.ProtoReflect.Descriptor instead.
func (*BestSellingProductsBatch) Descriptor() ([]byte, []int) {
	return file_best_selling_products_proto_rawDescGZIP(), []int{1}
}

func (x *BestSellingProductsBatch) GetItems() []*BestSellingProducts {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_best_selling_products_proto protoreflect.FileDescriptor

const file_best_selling_products_proto_rawDesc = "" +
	"\n" +
	"\x1bbest_selling_products.proto\x12\bprotocol\"\x84\x01\n" +
	"\x13BestSellingProducts\x121\n" +
	"\x15year_month_created_at\x18\x01 \x01(\tR\x12yearMonthCreatedAt\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12!\n" +
	"\fsellings_qty\x18\x03 \x01(\x03R\vsellingsQty\"O\n" +
	"\x18BestSellingProductsBatch\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.protocol.BestSellingProductsR\x05itemsB\x13Z\x11./reduced;reducedb\x06proto3"

var (
	file_best_selling_products_proto_rawDescOnce sync.Once
	file_best_selling_products_proto_rawDescData []byte
)

func file_best_selling_products_proto_rawDescGZIP() []byte {
	file_best_selling_products_proto_rawDescOnce.Do(func() {
		file_best_selling_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_best_selling_products_proto_rawDesc), len(file_best_selling_products_proto_rawDesc)))
	})
	return file_best_selling_products_proto_rawDescData
}

var file_best_selling_products_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_best_selling_products_proto_goTypes = []any{
	(*BestSellingProducts)(nil),      // 0: protocol.BestSellingProducts
	(*BestSellingProductsBatch)(nil), // 1: protocol.BestSellingProductsBatch
}
var file_best_selling_products_proto_depIdxs = []int32{
	0, // 0: protocol.BestSellingProductsBatch.items:type_name -> protocol.BestSellingProducts
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_best_selling_products_proto_init() }
func file_best_selling_products_proto_init() {
	if File_best_selling_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_best_selling_products_proto_rawDesc), len(file_best_selling_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_best_selling_products_proto_goTypes,
		DependencyIndexes: file_best_selling_products_proto_depIdxs,
		MessageInfos:      file_best_selling_products_proto_msgTypes,
	}.Build()
	File_best_selling_products_proto = out.File
	file_best_selling_products_proto_goTypes = nil
	file_best_selling_products_proto_depIdxs = nil
}
