// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: reduced/counted_user_transactions.proto

package reduced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CountedUserTransactions struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	StoreId             string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UserId              string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TransactionQuantity int32                  `protobuf:"varint,3,opt,name=transaction_quantity,json=transactionQuantity,proto3" json:"transaction_quantity,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CountedUserTransactions) Reset() {
	*x = CountedUserTransactions{}
	mi := &file_reduced_counted_user_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountedUserTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountedUserTransactions) ProtoMessage() {}

func (x *CountedUserTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_counted_user_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountedUserTransactions.ProtoReflect.Descriptor instead.
func (*CountedUserTransactions) Descriptor() ([]byte, []int) {
	return file_reduced_counted_user_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *CountedUserTransactions) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *CountedUserTransactions) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CountedUserTransactions) GetTransactionQuantity() int32 {
	if x != nil {
		return x.TransactionQuantity
	}
	return 0
}

var File_reduced_counted_user_transactions_proto protoreflect.FileDescriptor

const file_reduced_counted_user_transactions_proto_rawDesc = "" +
	"\n" +
	"'reduced/counted_user_transactions.proto\x12\areduced\"\x80\x01\n" +
	"\x17CountedUserTransactions\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x121\n" +
	"\x14transaction_quantity\x18\x03 \x01(\x05R\x13transactionQuantityB\vZ\t./reducedb\x06proto3"

var (
	file_reduced_counted_user_transactions_proto_rawDescOnce sync.Once
	file_reduced_counted_user_transactions_proto_rawDescData []byte
)

func file_reduced_counted_user_transactions_proto_rawDescGZIP() []byte {
	file_reduced_counted_user_transactions_proto_rawDescOnce.Do(func() {
		file_reduced_counted_user_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reduced_counted_user_transactions_proto_rawDesc), len(file_reduced_counted_user_transactions_proto_rawDesc)))
	})
	return file_reduced_counted_user_transactions_proto_rawDescData
}

var file_reduced_counted_user_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_reduced_counted_user_transactions_proto_goTypes = []any{
	(*CountedUserTransactions)(nil), // 0: reduced.CountedUserTransactions
}
var file_reduced_counted_user_transactions_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reduced_counted_user_transactions_proto_init() }
func file_reduced_counted_user_transactions_proto_init() {
	if File_reduced_counted_user_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reduced_counted_user_transactions_proto_rawDesc), len(file_reduced_counted_user_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reduced_counted_user_transactions_proto_goTypes,
		DependencyIndexes: file_reduced_counted_user_transactions_proto_depIdxs,
		MessageInfos:      file_reduced_counted_user_transactions_proto_msgTypes,
	}.Build()
	File_reduced_counted_user_transactions_proto = out.File
	file_reduced_counted_user_transactions_proto_goTypes = nil
	file_reduced_counted_user_transactions_proto_depIdxs = nil
}
