// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: reduced/total_payment_value.proto

package reduced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TotalPaymentValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       string                 `protobuf:"bytes,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Semester      string                 `protobuf:"bytes,2,opt,name=semester,proto3" json:"semester,omitempty"`
	FinalAmount   float64                `protobuf:"fixed64,3,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalPaymentValue) Reset() {
	*x = TotalPaymentValue{}
	mi := &file_reduced_total_payment_value_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalPaymentValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalPaymentValue) ProtoMessage() {}

func (x *TotalPaymentValue) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_payment_value_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalPaymentValue.ProtoReflect.Descriptor instead.
func (*TotalPaymentValue) Descriptor() ([]byte, []int) {
	return file_reduced_total_payment_value_proto_rawDescGZIP(), []int{0}
}

func (x *TotalPaymentValue) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *TotalPaymentValue) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *TotalPaymentValue) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

type TotalPaymentValueBatch struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TotalPaymentValues []*TotalPaymentValue   `protobuf:"bytes,1,rep,name=totalPaymentValues,proto3" json:"totalPaymentValues,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *TotalPaymentValueBatch) Reset() {
	*x = TotalPaymentValueBatch{}
	mi := &file_reduced_total_payment_value_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalPaymentValueBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalPaymentValueBatch) ProtoMessage() {}

func (x *TotalPaymentValueBatch) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_payment_value_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalPaymentValueBatch.ProtoReflect.Descriptor instead.
func (*TotalPaymentValueBatch) Descriptor() ([]byte, []int) {
	return file_reduced_total_payment_value_proto_rawDescGZIP(), []int{1}
}

func (x *TotalPaymentValueBatch) GetTotalPaymentValues() []*TotalPaymentValue {
	if x != nil {
		return x.TotalPaymentValues
	}
	return nil
}

var File_reduced_total_payment_value_proto protoreflect.FileDescriptor

const file_reduced_total_payment_value_proto_rawDesc = "" +
	"\n" +
	"!reduced/total_payment_value.proto\x12\areduced\"m\n" +
	"\x11TotalPaymentValue\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\tR\astoreId\x12\x1a\n" +
	"\bsemester\x18\x02 \x01(\tR\bsemester\x12!\n" +
	"\ffinal_amount\x18\x03 \x01(\x01R\vfinalAmount\"d\n" +
	"\x16TotalPaymentValueBatch\x12J\n" +
	"\x12totalPaymentValues\x18\x01 \x03(\v2\x1a.reduced.TotalPaymentValueR\x12totalPaymentValuesB\vZ\t./reducedb\x06proto3"

var (
	file_reduced_total_payment_value_proto_rawDescOnce sync.Once
	file_reduced_total_payment_value_proto_rawDescData []byte
)

func file_reduced_total_payment_value_proto_rawDescGZIP() []byte {
	file_reduced_total_payment_value_proto_rawDescOnce.Do(func() {
		file_reduced_total_payment_value_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reduced_total_payment_value_proto_rawDesc), len(file_reduced_total_payment_value_proto_rawDesc)))
	})
	return file_reduced_total_payment_value_proto_rawDescData
}

var file_reduced_total_payment_value_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reduced_total_payment_value_proto_goTypes = []any{
	(*TotalPaymentValue)(nil),      // 0: reduced.TotalPaymentValue
	(*TotalPaymentValueBatch)(nil), // 1: reduced.TotalPaymentValueBatch
}
var file_reduced_total_payment_value_proto_depIdxs = []int32{
	0, // 0: reduced.TotalPaymentValueBatch.totalPaymentValues:type_name -> reduced.TotalPaymentValue
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reduced_total_payment_value_proto_init() }
func file_reduced_total_payment_value_proto_init() {
	if File_reduced_total_payment_value_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reduced_total_payment_value_proto_rawDesc), len(file_reduced_total_payment_value_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reduced_total_payment_value_proto_goTypes,
		DependencyIndexes: file_reduced_total_payment_value_proto_depIdxs,
		MessageInfos:      file_reduced_total_payment_value_proto_msgTypes,
	}.Build()
	File_reduced_total_payment_value_proto = out.File
	file_reduced_total_payment_value_proto_goTypes = nil
	file_reduced_total_payment_value_proto_depIdxs = nil
}
