// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: reduced/total_profit_by_subtotal.proto

package reduced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TotalProfitBySubtotal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	YearMonth     string                 `protobuf:"bytes,2,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalProfitBySubtotal) Reset() {
	*x = TotalProfitBySubtotal{}
	mi := &file_reduced_total_profit_by_subtotal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalProfitBySubtotal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalProfitBySubtotal) ProtoMessage() {}

func (x *TotalProfitBySubtotal) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_profit_by_subtotal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalProfitBySubtotal.ProtoReflect.Descriptor instead.
func (*TotalProfitBySubtotal) Descriptor() ([]byte, []int) {
	return file_reduced_total_profit_by_subtotal_proto_rawDescGZIP(), []int{0}
}

func (x *TotalProfitBySubtotal) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TotalProfitBySubtotal) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

func (x *TotalProfitBySubtotal) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

type TotalProfitBySubtotalBatch struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	TotalProfitBySubtotals []*TotalProfitBySubtotal `protobuf:"bytes,1,rep,name=totalProfitBySubtotals,proto3" json:"totalProfitBySubtotals,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TotalProfitBySubtotalBatch) Reset() {
	*x = TotalProfitBySubtotalBatch{}
	mi := &file_reduced_total_profit_by_subtotal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalProfitBySubtotalBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalProfitBySubtotalBatch) ProtoMessage() {}

func (x *TotalProfitBySubtotalBatch) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_profit_by_subtotal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalProfitBySubtotalBatch.ProtoReflect.Descriptor instead.
func (*TotalProfitBySubtotalBatch) Descriptor() ([]byte, []int) {
	return file_reduced_total_profit_by_subtotal_proto_rawDescGZIP(), []int{1}
}

func (x *TotalProfitBySubtotalBatch) GetTotalProfitBySubtotals() []*TotalProfitBySubtotal {
	if x != nil {
		return x.TotalProfitBySubtotals
	}
	return nil
}

var File_reduced_total_profit_by_subtotal_proto protoreflect.FileDescriptor

const file_reduced_total_profit_by_subtotal_proto_rawDesc = "" +
	"\n" +
	"&reduced/total_profit_by_subtotal.proto\x12\areduced\"k\n" +
	"\x15TotalProfitBySubtotal\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"year_month\x18\x02 \x01(\tR\tyearMonth\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x01R\bsubtotal\"t\n" +
	"\x1aTotalProfitBySubtotalBatch\x12V\n" +
	"\x16totalProfitBySubtotals\x18\x01 \x03(\v2\x1e.reduced.TotalProfitBySubtotalR\x16totalProfitBySubtotalsB\vZ\t./reducedb\x06proto3"

var (
	file_reduced_total_profit_by_subtotal_proto_rawDescOnce sync.Once
	file_reduced_total_profit_by_subtotal_proto_rawDescData []byte
)

func file_reduced_total_profit_by_subtotal_proto_rawDescGZIP() []byte {
	file_reduced_total_profit_by_subtotal_proto_rawDescOnce.Do(func() {
		file_reduced_total_profit_by_subtotal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reduced_total_profit_by_subtotal_proto_rawDesc), len(file_reduced_total_profit_by_subtotal_proto_rawDesc)))
	})
	return file_reduced_total_profit_by_subtotal_proto_rawDescData
}

var file_reduced_total_profit_by_subtotal_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reduced_total_profit_by_subtotal_proto_goTypes = []any{
	(*TotalProfitBySubtotal)(nil),      // 0: reduced.TotalProfitBySubtotal
	(*TotalProfitBySubtotalBatch)(nil), // 1: reduced.TotalProfitBySubtotalBatch
}
var file_reduced_total_profit_by_subtotal_proto_depIdxs = []int32{
	0, // 0: reduced.TotalProfitBySubtotalBatch.totalProfitBySubtotals:type_name -> reduced.TotalProfitBySubtotal
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reduced_total_profit_by_subtotal_proto_init() }
func file_reduced_total_profit_by_subtotal_proto_init() {
	if File_reduced_total_profit_by_subtotal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reduced_total_profit_by_subtotal_proto_rawDesc), len(file_reduced_total_profit_by_subtotal_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reduced_total_profit_by_subtotal_proto_goTypes,
		DependencyIndexes: file_reduced_total_profit_by_subtotal_proto_depIdxs,
		MessageInfos:      file_reduced_total_profit_by_subtotal_proto_msgTypes,
	}.Build()
	File_reduced_total_profit_by_subtotal_proto = out.File
	file_reduced_total_profit_by_subtotal_proto_goTypes = nil
	file_reduced_total_profit_by_subtotal_proto_depIdxs = nil
}
