// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: reduced/total_sum_items.proto

package reduced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TotalSumItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	YearMonth     string                 `protobuf:"bytes,2,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalSumItem) Reset() {
	*x = TotalSumItem{}
	mi := &file_reduced_total_sum_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalSumItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSumItem) ProtoMessage() {}

func (x *TotalSumItem) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_sum_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSumItem.ProtoReflect.Descriptor instead.
func (*TotalSumItem) Descriptor() ([]byte, []int) {
	return file_reduced_total_sum_items_proto_rawDescGZIP(), []int{0}
}

func (x *TotalSumItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TotalSumItem) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

func (x *TotalSumItem) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *TotalSumItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TotalSumItemsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalSumItems []*TotalSumItem        `protobuf:"bytes,1,rep,name=totalSumItems,proto3" json:"totalSumItems,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalSumItemsBatch) Reset() {
	*x = TotalSumItemsBatch{}
	mi := &file_reduced_total_sum_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalSumItemsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSumItemsBatch) ProtoMessage() {}

func (x *TotalSumItemsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_sum_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSumItemsBatch.ProtoReflect.Descriptor instead.
func (*TotalSumItemsBatch) Descriptor() ([]byte, []int) {
	return file_reduced_total_sum_items_proto_rawDescGZIP(), []int{1}
}

func (x *TotalSumItemsBatch) GetTotalSumItems() []*TotalSumItem {
	if x != nil {
		return x.TotalSumItems
	}
	return nil
}

type TotalSumItemsReport struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	TotalSumItemsByQuantity []*TotalSumItem        `protobuf:"bytes,1,rep,name=totalSumItemsByQuantity,proto3" json:"totalSumItemsByQuantity,omitempty"`
	TotalSumItemsBySubtotal []*TotalSumItem        `protobuf:"bytes,2,rep,name=totalSumItemsBySubtotal,proto3" json:"totalSumItemsBySubtotal,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *TotalSumItemsReport) Reset() {
	*x = TotalSumItemsReport{}
	mi := &file_reduced_total_sum_items_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalSumItemsReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSumItemsReport) ProtoMessage() {}

func (x *TotalSumItemsReport) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_sum_items_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSumItemsReport.ProtoReflect.Descriptor instead.
func (*TotalSumItemsReport) Descriptor() ([]byte, []int) {
	return file_reduced_total_sum_items_proto_rawDescGZIP(), []int{2}
}

func (x *TotalSumItemsReport) GetTotalSumItemsByQuantity() []*TotalSumItem {
	if x != nil {
		return x.TotalSumItemsByQuantity
	}
	return nil
}

func (x *TotalSumItemsReport) GetTotalSumItemsBySubtotal() []*TotalSumItem {
	if x != nil {
		return x.TotalSumItemsBySubtotal
	}
	return nil
}

var File_reduced_total_sum_items_proto protoreflect.FileDescriptor

const file_reduced_total_sum_items_proto_rawDesc = "" +
	"\n" +
	"\x1dreduced/total_sum_items.proto\x12\areduced\"~\n" +
	"\fTotalSumItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"year_month\x18\x02 \x01(\tR\tyearMonth\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x01R\bsubtotal\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\"Q\n" +
	"\x12TotalSumItemsBatch\x12;\n" +
	"\rtotalSumItems\x18\x01 \x03(\v2\x15.reduced.TotalSumItemR\rtotalSumItems\"\xb7\x01\n" +
	"\x13TotalSumItemsReport\x12O\n" +
	"\x17totalSumItemsByQuantity\x18\x01 \x03(\v2\x15.reduced.TotalSumItemR\x17totalSumItemsByQuantity\x12O\n" +
	"\x17totalSumItemsBySubtotal\x18\x02 \x03(\v2\x15.reduced.TotalSumItemR\x17totalSumItemsBySubtotalB\vZ\t./reducedb\x06proto3"

var (
	file_reduced_total_sum_items_proto_rawDescOnce sync.Once
	file_reduced_total_sum_items_proto_rawDescData []byte
)

func file_reduced_total_sum_items_proto_rawDescGZIP() []byte {
	file_reduced_total_sum_items_proto_rawDescOnce.Do(func() {
		file_reduced_total_sum_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reduced_total_sum_items_proto_rawDesc), len(file_reduced_total_sum_items_proto_rawDesc)))
	})
	return file_reduced_total_sum_items_proto_rawDescData
}

var file_reduced_total_sum_items_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_reduced_total_sum_items_proto_goTypes = []any{
	(*TotalSumItem)(nil),        // 0: reduced.TotalSumItem
	(*TotalSumItemsBatch)(nil),  // 1: reduced.TotalSumItemsBatch
	(*TotalSumItemsReport)(nil), // 2: reduced.TotalSumItemsReport
}
var file_reduced_total_sum_items_proto_depIdxs = []int32{
	0, // 0: reduced.TotalSumItemsBatch.totalSumItems:type_name -> reduced.TotalSumItem
	0, // 1: reduced.TotalSumItemsReport.totalSumItemsByQuantity:type_name -> reduced.TotalSumItem
	0, // 2: reduced.TotalSumItemsReport.totalSumItemsBySubtotal:type_name -> reduced.TotalSumItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_reduced_total_sum_items_proto_init() }
func file_reduced_total_sum_items_proto_init() {
	if File_reduced_total_sum_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reduced_total_sum_items_proto_rawDesc), len(file_reduced_total_sum_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reduced_total_sum_items_proto_goTypes,
		DependencyIndexes: file_reduced_total_sum_items_proto_depIdxs,
		MessageInfos:      file_reduced_total_sum_items_proto_msgTypes,
	}.Build()
	File_reduced_total_sum_items_proto = out.File
	file_reduced_total_sum_items_proto_goTypes = nil
	file_reduced_total_sum_items_proto_depIdxs = nil
}
