// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: reduced/total_sold_by_quantity.proto

package reduced

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TotalSoldByQuantity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	YearMonth     string                 `protobuf:"bytes,2,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TotalSoldByQuantity) Reset() {
	*x = TotalSoldByQuantity{}
	mi := &file_reduced_total_sold_by_quantity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalSoldByQuantity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSoldByQuantity) ProtoMessage() {}

func (x *TotalSoldByQuantity) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_sold_by_quantity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSoldByQuantity.ProtoReflect.Descriptor instead.
func (*TotalSoldByQuantity) Descriptor() ([]byte, []int) {
	return file_reduced_total_sold_by_quantity_proto_rawDescGZIP(), []int{0}
}

func (x *TotalSoldByQuantity) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TotalSoldByQuantity) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

func (x *TotalSoldByQuantity) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type TotalSoldByQuantityBatch struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	TotalSoldByQuantities []*TotalSoldByQuantity `protobuf:"bytes,1,rep,name=totalSoldByQuantities,proto3" json:"totalSoldByQuantities,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *TotalSoldByQuantityBatch) Reset() {
	*x = TotalSoldByQuantityBatch{}
	mi := &file_reduced_total_sold_by_quantity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TotalSoldByQuantityBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TotalSoldByQuantityBatch) ProtoMessage() {}

func (x *TotalSoldByQuantityBatch) ProtoReflect() protoreflect.Message {
	mi := &file_reduced_total_sold_by_quantity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TotalSoldByQuantityBatch.ProtoReflect.Descriptor instead.
func (*TotalSoldByQuantityBatch) Descriptor() ([]byte, []int) {
	return file_reduced_total_sold_by_quantity_proto_rawDescGZIP(), []int{1}
}

func (x *TotalSoldByQuantityBatch) GetTotalSoldByQuantities() []*TotalSoldByQuantity {
	if x != nil {
		return x.TotalSoldByQuantities
	}
	return nil
}

var File_reduced_total_sold_by_quantity_proto protoreflect.FileDescriptor

const file_reduced_total_sold_by_quantity_proto_rawDesc = "" +
	"\n" +
	"$reduced/total_sold_by_quantity.proto\x12\areduced\"i\n" +
	"\x13TotalSoldByQuantity\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"year_month\x18\x02 \x01(\tR\tyearMonth\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\"n\n" +
	"\x18TotalSoldByQuantityBatch\x12R\n" +
	"\x15totalSoldByQuantities\x18\x01 \x03(\v2\x1c.reduced.TotalSoldByQuantityR\x15totalSoldByQuantitiesB\vZ\t./reducedb\x06proto3"

var (
	file_reduced_total_sold_by_quantity_proto_rawDescOnce sync.Once
	file_reduced_total_sold_by_quantity_proto_rawDescData []byte
)

func file_reduced_total_sold_by_quantity_proto_rawDescGZIP() []byte {
	file_reduced_total_sold_by_quantity_proto_rawDescOnce.Do(func() {
		file_reduced_total_sold_by_quantity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_reduced_total_sold_by_quantity_proto_rawDesc), len(file_reduced_total_sold_by_quantity_proto_rawDesc)))
	})
	return file_reduced_total_sold_by_quantity_proto_rawDescData
}

var file_reduced_total_sold_by_quantity_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reduced_total_sold_by_quantity_proto_goTypes = []any{
	(*TotalSoldByQuantity)(nil),      // 0: reduced.TotalSoldByQuantity
	(*TotalSoldByQuantityBatch)(nil), // 1: reduced.TotalSoldByQuantityBatch
}
var file_reduced_total_sold_by_quantity_proto_depIdxs = []int32{
	0, // 0: reduced.TotalSoldByQuantityBatch.totalSoldByQuantities:type_name -> reduced.TotalSoldByQuantity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_reduced_total_sold_by_quantity_proto_init() }
func file_reduced_total_sold_by_quantity_proto_init() {
	if File_reduced_total_sold_by_quantity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reduced_total_sold_by_quantity_proto_rawDesc), len(file_reduced_total_sold_by_quantity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reduced_total_sold_by_quantity_proto_goTypes,
		DependencyIndexes: file_reduced_total_sold_by_quantity_proto_depIdxs,
		MessageInfos:      file_reduced_total_sold_by_quantity_proto_msgTypes,
	}.Build()
	File_reduced_total_sold_by_quantity_proto = out.File
	file_reduced_total_sold_by_quantity_proto_goTypes = nil
	file_reduced_total_sold_by_quantity_proto_depIdxs = nil
}
