// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: group_by/group_transaction_items.proto

package group_by

import (
	raw "github.com/maxogod/distro-tp/src/common/models/raw"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupTransactionItems struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ItemId           string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	YearMonth        string                 `protobuf:"bytes,2,opt,name=year_month,json=yearMonth,proto3" json:"year_month,omitempty"`
	TransactionItems []*raw.TransactionItem `protobuf:"bytes,3,rep,name=transaction_items,json=transactionItems,proto3" json:"transaction_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupTransactionItems) Reset() {
	*x = GroupTransactionItems{}
	mi := &file_group_by_group_transaction_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTransactionItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTransactionItems) ProtoMessage() {}

func (x *GroupTransactionItems) ProtoReflect() protoreflect.Message {
	mi := &file_group_by_group_transaction_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTransactionItems.ProtoReflect.Descriptor instead.
func (*GroupTransactionItems) Descriptor() ([]byte, []int) {
	return file_group_by_group_transaction_items_proto_rawDescGZIP(), []int{0}
}

func (x *GroupTransactionItems) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *GroupTransactionItems) GetYearMonth() string {
	if x != nil {
		return x.YearMonth
	}
	return ""
}

func (x *GroupTransactionItems) GetTransactionItems() []*raw.TransactionItem {
	if x != nil {
		return x.TransactionItems
	}
	return nil
}

type GroupTransactionItemsBatch struct {
	state                 protoimpl.MessageState   `protogen:"open.v1"`
	GroupTransactionItems []*GroupTransactionItems `protobuf:"bytes,1,rep,name=group_transaction_items,json=groupTransactionItems,proto3" json:"group_transaction_items,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GroupTransactionItemsBatch) Reset() {
	*x = GroupTransactionItemsBatch{}
	mi := &file_group_by_group_transaction_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTransactionItemsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTransactionItemsBatch) ProtoMessage() {}

func (x *GroupTransactionItemsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_group_by_group_transaction_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTransactionItemsBatch.ProtoReflect.Descriptor instead.
func (*GroupTransactionItemsBatch) Descriptor() ([]byte, []int) {
	return file_group_by_group_transaction_items_proto_rawDescGZIP(), []int{1}
}

func (x *GroupTransactionItemsBatch) GetGroupTransactionItems() []*GroupTransactionItems {
	if x != nil {
		return x.GroupTransactionItems
	}
	return nil
}

var File_group_by_group_transaction_items_proto protoreflect.FileDescriptor

const file_group_by_group_transaction_items_proto_rawDesc = "" +
	"\n" +
	"&group_by/group_transaction_items.proto\x12\bgroup_by\x1a\x1araw/transaction_item.proto\"\x92\x01\n" +
	"\x15GroupTransactionItems\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1d\n" +
	"\n" +
	"year_month\x18\x02 \x01(\tR\tyearMonth\x12A\n" +
	"\x11transaction_items\x18\x03 \x03(\v2\x14.raw.TransactionItemR\x10transactionItems\"u\n" +
	"\x1aGroupTransactionItemsBatch\x12W\n" +
	"\x17group_transaction_items\x18\x01 \x03(\v2\x1f.group_by.GroupTransactionItemsR\x15groupTransactionItemsB\fZ\n" +
	"./group_byb\x06proto3"

var (
	file_group_by_group_transaction_items_proto_rawDescOnce sync.Once
	file_group_by_group_transaction_items_proto_rawDescData []byte
)

func file_group_by_group_transaction_items_proto_rawDescGZIP() []byte {
	file_group_by_group_transaction_items_proto_rawDescOnce.Do(func() {
		file_group_by_group_transaction_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_by_group_transaction_items_proto_rawDesc), len(file_group_by_group_transaction_items_proto_rawDesc)))
	})
	return file_group_by_group_transaction_items_proto_rawDescData
}

var file_group_by_group_transaction_items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_group_by_group_transaction_items_proto_goTypes = []any{
	(*GroupTransactionItems)(nil),      // 0: group_by.GroupTransactionItems
	(*GroupTransactionItemsBatch)(nil), // 1: group_by.GroupTransactionItemsBatch
	(*raw.TransactionItem)(nil),        // 2: raw.TransactionItem
}
var file_group_by_group_transaction_items_proto_depIdxs = []int32{
	2, // 0: group_by.GroupTransactionItems.transaction_items:type_name -> raw.TransactionItem
	0, // 1: group_by.GroupTransactionItemsBatch.group_transaction_items:type_name -> group_by.GroupTransactionItems
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_group_by_group_transaction_items_proto_init() }
func file_group_by_group_transaction_items_proto_init() {
	if File_group_by_group_transaction_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_by_group_transaction_items_proto_rawDesc), len(file_group_by_group_transaction_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_by_group_transaction_items_proto_goTypes,
		DependencyIndexes: file_group_by_group_transaction_items_proto_depIdxs,
		MessageInfos:      file_group_by_group_transaction_items_proto_msgTypes,
	}.Build()
	File_group_by_group_transaction_items_proto = out.File
	file_group_by_group_transaction_items_proto_goTypes = nil
	file_group_by_group_transaction_items_proto_depIdxs = nil
}
