// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: group_by/group_transactions.proto

package group_by

import (
	raw "github.com/maxogod/distro-tp/src/common/models/raw"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GroupTransactions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Semester      string                 `protobuf:"bytes,4,opt,name=semester,proto3" json:"semester,omitempty"`
	Transactions  []*raw.Transaction     `protobuf:"bytes,5,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupTransactions) Reset() {
	*x = GroupTransactions{}
	mi := &file_group_by_group_transactions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupTransactions) ProtoMessage() {}

func (x *GroupTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_group_by_group_transactions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupTransactions.ProtoReflect.Descriptor instead.
func (*GroupTransactions) Descriptor() ([]byte, []int) {
	return file_group_by_group_transactions_proto_rawDescGZIP(), []int{0}
}

func (x *GroupTransactions) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GroupTransactions) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *GroupTransactions) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupTransactions) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *GroupTransactions) GetTransactions() []*raw.Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_group_by_group_transactions_proto protoreflect.FileDescriptor

const file_group_by_group_transactions_proto_rawDesc = "" +
	"\n" +
	"!group_by/group_transactions.proto\x12\bgroup_by\x1a\x15raw/transaction.proto\"\xc0\x01\n" +
	"\x11GroupTransactions\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1a\n" +
	"\bsemester\x18\x04 \x01(\tR\bsemester\x124\n" +
	"\ftransactions\x18\x05 \x03(\v2\x10.raw.TransactionR\ftransactionsB\fZ\n" +
	"./group_byb\x06proto3"

var (
	file_group_by_group_transactions_proto_rawDescOnce sync.Once
	file_group_by_group_transactions_proto_rawDescData []byte
)

func file_group_by_group_transactions_proto_rawDescGZIP() []byte {
	file_group_by_group_transactions_proto_rawDescOnce.Do(func() {
		file_group_by_group_transactions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_group_by_group_transactions_proto_rawDesc), len(file_group_by_group_transactions_proto_rawDesc)))
	})
	return file_group_by_group_transactions_proto_rawDescData
}

var file_group_by_group_transactions_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_group_by_group_transactions_proto_goTypes = []any{
	(*GroupTransactions)(nil), // 0: group_by.GroupTransactions
	(*raw.Transaction)(nil),   // 1: raw.Transaction
}
var file_group_by_group_transactions_proto_depIdxs = []int32{
	1, // 0: group_by.GroupTransactions.transactions:type_name -> raw.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_group_by_group_transactions_proto_init() }
func file_group_by_group_transactions_proto_init() {
	if File_group_by_group_transactions_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_group_by_group_transactions_proto_rawDesc), len(file_group_by_group_transactions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_group_by_group_transactions_proto_goTypes,
		DependencyIndexes: file_group_by_group_transactions_proto_depIdxs,
		MessageInfos:      file_group_by_group_transactions_proto_msgTypes,
	}.Build()
	File_group_by_group_transactions_proto = out.File
	file_group_by_group_transactions_proto_goTypes = nil
	file_group_by_group_transactions_proto_depIdxs = nil
}
