// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: data_transfer/aggregator_data.proto

package data_transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AggregatorData struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	FinishingClients []string               `protobuf:"bytes,1,rep,name=finishingClients,proto3" json:"finishingClients,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AggregatorData) Reset() {
	*x = AggregatorData{}
	mi := &file_data_transfer_aggregator_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AggregatorData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AggregatorData) ProtoMessage() {}

func (x *AggregatorData) ProtoReflect() protoreflect.Message {
	mi := &file_data_transfer_aggregator_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AggregatorData.ProtoReflect.Descriptor instead.
func (*AggregatorData) Descriptor() ([]byte, []int) {
	return file_data_transfer_aggregator_data_proto_rawDescGZIP(), []int{0}
}

func (x *AggregatorData) GetFinishingClients() []string {
	if x != nil {
		return x.FinishingClients
	}
	return nil
}

var File_data_transfer_aggregator_data_proto protoreflect.FileDescriptor

const file_data_transfer_aggregator_data_proto_rawDesc = "" +
	"\n" +
	"#data_transfer/aggregator_data.proto\x12\rdata_transfer\"<\n" +
	"\x0eAggregatorData\x12*\n" +
	"\x10finishingClients\x18\x01 \x03(\tR\x10finishingClientsB\x11Z\x0f./data_transferb\x06proto3"

var (
	file_data_transfer_aggregator_data_proto_rawDescOnce sync.Once
	file_data_transfer_aggregator_data_proto_rawDescData []byte
)

func file_data_transfer_aggregator_data_proto_rawDescGZIP() []byte {
	file_data_transfer_aggregator_data_proto_rawDescOnce.Do(func() {
		file_data_transfer_aggregator_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_data_transfer_aggregator_data_proto_rawDesc), len(file_data_transfer_aggregator_data_proto_rawDesc)))
	})
	return file_data_transfer_aggregator_data_proto_rawDescData
}

var file_data_transfer_aggregator_data_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_data_transfer_aggregator_data_proto_goTypes = []any{
	(*AggregatorData)(nil), // 0: data_transfer.AggregatorData
}
var file_data_transfer_aggregator_data_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_data_transfer_aggregator_data_proto_init() }
func file_data_transfer_aggregator_data_proto_init() {
	if File_data_transfer_aggregator_data_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_data_transfer_aggregator_data_proto_rawDesc), len(file_data_transfer_aggregator_data_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_data_transfer_aggregator_data_proto_goTypes,
		DependencyIndexes: file_data_transfer_aggregator_data_proto_depIdxs,
		MessageInfos:      file_data_transfer_aggregator_data_proto_msgTypes,
	}.Build()
	File_data_transfer_aggregator_data_proto = out.File
	file_data_transfer_aggregator_data_proto_goTypes = nil
	file_data_transfer_aggregator_data_proto_depIdxs = nil
}
