// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: src/common/protobufs/menu_items.proto

package menu_items

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	IsSeasonal    bool                   `protobuf:"varint,5,opt,name=is_seasonal,json=isSeasonal,proto3" json:"is_seasonal,omitempty"`
	AvailableFrom string                 `protobuf:"bytes,6,opt,name=available_from,json=availableFrom,proto3" json:"available_from,omitempty"` // ISO 8601 format
	AvailableTo   string                 `protobuf:"bytes,7,opt,name=available_to,json=availableTo,proto3" json:"available_to,omitempty"`       // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_src_common_protobufs_menu_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protobufs_menu_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_src_common_protobufs_menu_items_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MenuItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *MenuItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetIsSeasonal() bool {
	if x != nil {
		return x.IsSeasonal
	}
	return false
}

func (x *MenuItem) GetAvailableFrom() string {
	if x != nil {
		return x.AvailableFrom
	}
	return ""
}

func (x *MenuItem) GetAvailableTo() string {
	if x != nil {
		return x.AvailableTo
	}
	return ""
}

type MenuItemBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItem      []*MenuItem            `protobuf:"bytes,1,rep,name=menu_item,json=menuItem,proto3" json:"menu_item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemBatch) Reset() {
	*x = MenuItemBatch{}
	mi := &file_src_common_protobufs_menu_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemBatch) ProtoMessage() {}

func (x *MenuItemBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protobufs_menu_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemBatch.ProtoReflect.Descriptor instead.
func (*MenuItemBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protobufs_menu_items_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItemBatch) GetMenuItem() []*MenuItem {
	if x != nil {
		return x.MenuItem
	}
	return nil
}

var File_src_common_protobufs_menu_items_proto protoreflect.FileDescriptor

const file_src_common_protobufs_menu_items_proto_rawDesc = "" +
	"\n" +
	"%src/common/protobufs/menu_items.proto\"\xdd\x01\n" +
	"\bMenuItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1f\n" +
	"\vis_seasonal\x18\x05 \x01(\bR\n" +
	"isSeasonal\x12%\n" +
	"\x0eavailable_from\x18\x06 \x01(\tR\ravailableFrom\x12!\n" +
	"\favailable_to\x18\a \x01(\tR\vavailableTo\"7\n" +
	"\rMenuItemBatch\x12&\n" +
	"\tmenu_item\x18\x01 \x03(\v2\t.MenuItemR\bmenuItemB\x0eZ\f./menu_itemsb\x06proto3"

var (
	file_src_common_protobufs_menu_items_proto_rawDescOnce sync.Once
	file_src_common_protobufs_menu_items_proto_rawDescData []byte
)

func file_src_common_protobufs_menu_items_proto_rawDescGZIP() []byte {
	file_src_common_protobufs_menu_items_proto_rawDescOnce.Do(func() {
		file_src_common_protobufs_menu_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protobufs_menu_items_proto_rawDesc), len(file_src_common_protobufs_menu_items_proto_rawDesc)))
	})
	return file_src_common_protobufs_menu_items_proto_rawDescData
}

var file_src_common_protobufs_menu_items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protobufs_menu_items_proto_goTypes = []any{
	(*MenuItem)(nil),      // 0: MenuItem
	(*MenuItemBatch)(nil), // 1: MenuItemBatch
}
var file_src_common_protobufs_menu_items_proto_depIdxs = []int32{
	0, // 0: MenuItemBatch.menu_item:type_name -> MenuItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protobufs_menu_items_proto_init() }
func file_src_common_protobufs_menu_items_proto_init() {
	if File_src_common_protobufs_menu_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protobufs_menu_items_proto_rawDesc), len(file_src_common_protobufs_menu_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protobufs_menu_items_proto_goTypes,
		DependencyIndexes: file_src_common_protobufs_menu_items_proto_depIdxs,
		MessageInfos:      file_src_common_protobufs_menu_items_proto_msgTypes,
	}.Build()
	File_src_common_protobufs_menu_items_proto = out.File
	file_src_common_protobufs_menu_items_proto_goTypes = nil
	file_src_common_protobufs_menu_items_proto_depIdxs = nil
}
