// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: src/common/protobufs/user.proto

package user

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate     string                 `protobuf:"bytes,3,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"` // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_src_common_protobufs_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protobufs_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_src_common_protobufs_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *User) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type UserBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionItems []*User                `protobuf:"bytes,1,rep,name=transaction_items,json=transactionItems,proto3" json:"transaction_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UserBatch) Reset() {
	*x = UserBatch{}
	mi := &file_src_common_protobufs_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserBatch) ProtoMessage() {}

func (x *UserBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protobufs_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserBatch.ProtoReflect.Descriptor instead.
func (*UserBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protobufs_user_proto_rawDescGZIP(), []int{1}
}

func (x *UserBatch) GetTransactionItems() []*User {
	if x != nil {
		return x.TransactionItems
	}
	return nil
}

var File_src_common_protobufs_user_proto protoreflect.FileDescriptor

const file_src_common_protobufs_user_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/common/protobufs/user.proto\"z\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x1c\n" +
	"\tbirthdate\x18\x03 \x01(\tR\tbirthdate\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\tR\fregisteredAt\"?\n" +
	"\tUserBatch\x122\n" +
	"\x11transaction_items\x18\x01 \x03(\v2\x05.UserR\x10transactionItemsB\bZ\x06./userb\x06proto3"

var (
	file_src_common_protobufs_user_proto_rawDescOnce sync.Once
	file_src_common_protobufs_user_proto_rawDescData []byte
)

func file_src_common_protobufs_user_proto_rawDescGZIP() []byte {
	file_src_common_protobufs_user_proto_rawDescOnce.Do(func() {
		file_src_common_protobufs_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protobufs_user_proto_rawDesc), len(file_src_common_protobufs_user_proto_rawDesc)))
	})
	return file_src_common_protobufs_user_proto_rawDescData
}

var file_src_common_protobufs_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protobufs_user_proto_goTypes = []any{
	(*User)(nil),      // 0: User
	(*UserBatch)(nil), // 1: UserBatch
}
var file_src_common_protobufs_user_proto_depIdxs = []int32{
	0, // 0: UserBatch.transaction_items:type_name -> User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protobufs_user_proto_init() }
func file_src_common_protobufs_user_proto_init() {
	if File_src_common_protobufs_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protobufs_user_proto_rawDesc), len(file_src_common_protobufs_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protobufs_user_proto_goTypes,
		DependencyIndexes: file_src_common_protobufs_user_proto_depIdxs,
		MessageInfos:      file_src_common_protobufs_user_proto_msgTypes,
	}.Build()
	File_src_common_protobufs_user_proto = out.File
	file_src_common_protobufs_user_proto_goTypes = nil
	file_src_common_protobufs_user_proto_depIdxs = nil
}
