// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/join_best_selling.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinBestSellingProducts struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	YearMonthCreatedAt string                 `protobuf:"bytes,1,opt,name=year_month_created_at,json=yearMonthCreatedAt,proto3" json:"year_month_created_at,omitempty"`
	ItemName           string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	SellingsQty        int64                  `protobuf:"varint,3,opt,name=sellings_qty,json=sellingsQty,proto3" json:"sellings_qty,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *JoinBestSellingProducts) Reset() {
	*x = JoinBestSellingProducts{}
	mi := &file_src_common_protocol_join_best_selling_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBestSellingProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBestSellingProducts) ProtoMessage() {}

func (x *JoinBestSellingProducts) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_join_best_selling_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBestSellingProducts.ProtoReflect.Descriptor instead.
func (*JoinBestSellingProducts) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_join_best_selling_proto_rawDescGZIP(), []int{0}
}

func (x *JoinBestSellingProducts) GetYearMonthCreatedAt() string {
	if x != nil {
		return x.YearMonthCreatedAt
	}
	return ""
}

func (x *JoinBestSellingProducts) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *JoinBestSellingProducts) GetSellingsQty() int64 {
	if x != nil {
		return x.SellingsQty
	}
	return 0
}

type JoinBestSellingProductsBatch struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Items         []*JoinBestSellingProducts `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinBestSellingProductsBatch) Reset() {
	*x = JoinBestSellingProductsBatch{}
	mi := &file_src_common_protocol_join_best_selling_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinBestSellingProductsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinBestSellingProductsBatch) ProtoMessage() {}

func (x *JoinBestSellingProductsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_join_best_selling_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinBestSellingProductsBatch.ProtoReflect.Descriptor instead.
func (*JoinBestSellingProductsBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_join_best_selling_proto_rawDescGZIP(), []int{1}
}

func (x *JoinBestSellingProductsBatch) GetItems() []*JoinBestSellingProducts {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_src_common_protocol_join_best_selling_proto protoreflect.FileDescriptor

const file_src_common_protocol_join_best_selling_proto_rawDesc = "" +
	"\n" +
	"+src/common/protocol/join_best_selling.proto\x12\bprotocol\"\x8c\x01\n" +
	"\x17JoinBestSellingProducts\x121\n" +
	"\x15year_month_created_at\x18\x01 \x01(\tR\x12yearMonthCreatedAt\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12!\n" +
	"\fsellings_qty\x18\x03 \x01(\x03R\vsellingsQty\"W\n" +
	"\x1cJoinBestSellingProductsBatch\x127\n" +
	"\x05items\x18\x01 \x03(\v2!.protocol.JoinBestSellingProductsR\x05itemsB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_join_best_selling_proto_rawDescOnce sync.Once
	file_src_common_protocol_join_best_selling_proto_rawDescData []byte
)

func file_src_common_protocol_join_best_selling_proto_rawDescGZIP() []byte {
	file_src_common_protocol_join_best_selling_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_join_best_selling_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_join_best_selling_proto_rawDesc), len(file_src_common_protocol_join_best_selling_proto_rawDesc)))
	})
	return file_src_common_protocol_join_best_selling_proto_rawDescData
}

var file_src_common_protocol_join_best_selling_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_join_best_selling_proto_goTypes = []any{
	(*JoinBestSellingProducts)(nil),      // 0: protocol.JoinBestSellingProducts
	(*JoinBestSellingProductsBatch)(nil), // 1: protocol.JoinBestSellingProductsBatch
}
var file_src_common_protocol_join_best_selling_proto_depIdxs = []int32{
	0, // 0: protocol.JoinBestSellingProductsBatch.items:type_name -> protocol.JoinBestSellingProducts
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protocol_join_best_selling_proto_init() }
func file_src_common_protocol_join_best_selling_proto_init() {
	if File_src_common_protocol_join_best_selling_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_join_best_selling_proto_rawDesc), len(file_src_common_protocol_join_best_selling_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_join_best_selling_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_join_best_selling_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_join_best_selling_proto_msgTypes,
	}.Build()
	File_src_common_protocol_join_best_selling_proto = out.File
	file_src_common_protocol_join_best_selling_proto_goTypes = nil
	file_src_common_protocol_join_best_selling_proto_depIdxs = nil
}
