// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/join_tpv.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinStoreTPV struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	YearHalfCreatedAt string                 `protobuf:"bytes,1,opt,name=year_half_created_at,json=yearHalfCreatedAt,proto3" json:"year_half_created_at,omitempty"`
	StoreName         string                 `protobuf:"bytes,2,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Tpv               int64                  `protobuf:"varint,3,opt,name=tpv,proto3" json:"tpv,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *JoinStoreTPV) Reset() {
	*x = JoinStoreTPV{}
	mi := &file_src_common_protocol_join_tpv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinStoreTPV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinStoreTPV) ProtoMessage() {}

func (x *JoinStoreTPV) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_join_tpv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinStoreTPV.ProtoReflect.Descriptor instead.
func (*JoinStoreTPV) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_join_tpv_proto_rawDescGZIP(), []int{0}
}

func (x *JoinStoreTPV) GetYearHalfCreatedAt() string {
	if x != nil {
		return x.YearHalfCreatedAt
	}
	return ""
}

func (x *JoinStoreTPV) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *JoinStoreTPV) GetTpv() int64 {
	if x != nil {
		return x.Tpv
	}
	return 0
}

type JoinStoreTPVBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*JoinStoreTPV        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinStoreTPVBatch) Reset() {
	*x = JoinStoreTPVBatch{}
	mi := &file_src_common_protocol_join_tpv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinStoreTPVBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinStoreTPVBatch) ProtoMessage() {}

func (x *JoinStoreTPVBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_join_tpv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinStoreTPVBatch.ProtoReflect.Descriptor instead.
func (*JoinStoreTPVBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_join_tpv_proto_rawDescGZIP(), []int{1}
}

func (x *JoinStoreTPVBatch) GetItems() []*JoinStoreTPV {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_src_common_protocol_join_tpv_proto protoreflect.FileDescriptor

const file_src_common_protocol_join_tpv_proto_rawDesc = "" +
	"\n" +
	"\"src/common/protocol/join_tpv.proto\x12\bprotocol\"p\n" +
	"\fJoinStoreTPV\x12/\n" +
	"\x14year_half_created_at\x18\x01 \x01(\tR\x11yearHalfCreatedAt\x12\x1d\n" +
	"\n" +
	"store_name\x18\x02 \x01(\tR\tstoreName\x12\x10\n" +
	"\x03tpv\x18\x03 \x01(\x03R\x03tpv\"A\n" +
	"\x11JoinStoreTPVBatch\x12,\n" +
	"\x05items\x18\x01 \x03(\v2\x16.protocol.JoinStoreTPVR\x05itemsB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_join_tpv_proto_rawDescOnce sync.Once
	file_src_common_protocol_join_tpv_proto_rawDescData []byte
)

func file_src_common_protocol_join_tpv_proto_rawDescGZIP() []byte {
	file_src_common_protocol_join_tpv_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_join_tpv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_join_tpv_proto_rawDesc), len(file_src_common_protocol_join_tpv_proto_rawDesc)))
	})
	return file_src_common_protocol_join_tpv_proto_rawDescData
}

var file_src_common_protocol_join_tpv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_join_tpv_proto_goTypes = []any{
	(*JoinStoreTPV)(nil),      // 0: protocol.JoinStoreTPV
	(*JoinStoreTPVBatch)(nil), // 1: protocol.JoinStoreTPVBatch
}
var file_src_common_protocol_join_tpv_proto_depIdxs = []int32{
	0, // 0: protocol.JoinStoreTPVBatch.items:type_name -> protocol.JoinStoreTPV
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protocol_join_tpv_proto_init() }
func file_src_common_protocol_join_tpv_proto_init() {
	if File_src_common_protocol_join_tpv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_join_tpv_proto_rawDesc), len(file_src_common_protocol_join_tpv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_join_tpv_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_join_tpv_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_join_tpv_proto_msgTypes,
	}.Build()
	File_src_common_protocol_join_tpv_proto = out.File
	file_src_common_protocol_join_tpv_proto_goTypes = nil
	file_src_common_protocol_join_tpv_proto_depIdxs = nil
}
