// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/menu_items.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        int32                  `protobuf:"varint,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	IsSeasonal    bool                   `protobuf:"varint,5,opt,name=is_seasonal,json=isSeasonal,proto3" json:"is_seasonal,omitempty"`
	AvailableFrom *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=available_from,json=availableFrom,proto3" json:"available_from,omitempty"`
	AvailableTo   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=available_to,json=availableTo,proto3" json:"available_to,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_src_common_protocol_menu_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_menu_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_menu_items_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MenuItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *MenuItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetIsSeasonal() bool {
	if x != nil {
		return x.IsSeasonal
	}
	return false
}

func (x *MenuItem) GetAvailableFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableFrom
	}
	return nil
}

func (x *MenuItem) GetAvailableTo() *timestamppb.Timestamp {
	if x != nil {
		return x.AvailableTo
	}
	return nil
}

type MenuItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItems) Reset() {
	*x = MenuItems{}
	mi := &file_src_common_protocol_menu_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItems) ProtoMessage() {}

func (x *MenuItems) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_menu_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItems.ProtoReflect.Descriptor instead.
func (*MenuItems) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_menu_items_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItems) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_src_common_protocol_menu_items_proto protoreflect.FileDescriptor

const file_src_common_protocol_menu_items_proto_rawDesc = "" +
	"\n" +
	"$src/common/protocol/menu_items.proto\x12\bprotocol\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x02\n" +
	"\bMenuItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\x05R\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1f\n" +
	"\vis_seasonal\x18\x05 \x01(\bR\n" +
	"isSeasonal\x12A\n" +
	"\x0eavailable_from\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ravailableFrom\x12=\n" +
	"\favailable_to\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\vavailableTo\"5\n" +
	"\tMenuItems\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.protocol.MenuItemR\x05itemsB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_menu_items_proto_rawDescOnce sync.Once
	file_src_common_protocol_menu_items_proto_rawDescData []byte
)

func file_src_common_protocol_menu_items_proto_rawDescGZIP() []byte {
	file_src_common_protocol_menu_items_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_menu_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_menu_items_proto_rawDesc), len(file_src_common_protocol_menu_items_proto_rawDesc)))
	})
	return file_src_common_protocol_menu_items_proto_rawDescData
}

var file_src_common_protocol_menu_items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_menu_items_proto_goTypes = []any{
	(*MenuItem)(nil),              // 0: protocol.MenuItem
	(*MenuItems)(nil),             // 1: protocol.MenuItems
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_src_common_protocol_menu_items_proto_depIdxs = []int32{
	2, // 0: protocol.MenuItem.available_from:type_name -> google.protobuf.Timestamp
	2, // 1: protocol.MenuItem.available_to:type_name -> google.protobuf.Timestamp
	0, // 2: protocol.MenuItems.items:type_name -> protocol.MenuItem
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_src_common_protocol_menu_items_proto_init() }
func file_src_common_protocol_menu_items_proto_init() {
	if File_src_common_protocol_menu_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_menu_items_proto_rawDesc), len(file_src_common_protocol_menu_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_menu_items_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_menu_items_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_menu_items_proto_msgTypes,
	}.Build()
	File_src_common_protocol_menu_items_proto = out.File
	file_src_common_protocol_menu_items_proto_goTypes = nil
	file_src_common_protocol_menu_items_proto_depIdxs = nil
}
