// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/most_profits_products.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MostProfitsProducts struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	YearMonthCreatedAt string                 `protobuf:"bytes,1,opt,name=year_month_created_at,json=yearMonthCreatedAt,proto3" json:"year_month_created_at,omitempty"`
	ItemId             int32                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ProfitSum          float64                `protobuf:"fixed64,3,opt,name=profit_sum,json=profitSum,proto3" json:"profit_sum,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MostProfitsProducts) Reset() {
	*x = MostProfitsProducts{}
	mi := &file_src_common_protocol_most_profits_products_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostProfitsProducts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostProfitsProducts) ProtoMessage() {}

func (x *MostProfitsProducts) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_most_profits_products_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostProfitsProducts.ProtoReflect.Descriptor instead.
func (*MostProfitsProducts) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_most_profits_products_proto_rawDescGZIP(), []int{0}
}

func (x *MostProfitsProducts) GetYearMonthCreatedAt() string {
	if x != nil {
		return x.YearMonthCreatedAt
	}
	return ""
}

func (x *MostProfitsProducts) GetItemId() int32 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *MostProfitsProducts) GetProfitSum() float64 {
	if x != nil {
		return x.ProfitSum
	}
	return 0
}

type MostProfitsProductsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MostProfitsProducts `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostProfitsProductsBatch) Reset() {
	*x = MostProfitsProductsBatch{}
	mi := &file_src_common_protocol_most_profits_products_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostProfitsProductsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostProfitsProductsBatch) ProtoMessage() {}

func (x *MostProfitsProductsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_most_profits_products_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostProfitsProductsBatch.ProtoReflect.Descriptor instead.
func (*MostProfitsProductsBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_most_profits_products_proto_rawDescGZIP(), []int{1}
}

func (x *MostProfitsProductsBatch) GetItems() []*MostProfitsProducts {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_src_common_protocol_most_profits_products_proto protoreflect.FileDescriptor

const file_src_common_protocol_most_profits_products_proto_rawDesc = "" +
	"\n" +
	"/src/common/protocol/most_profits_products.proto\x12\bprotocol\"\x80\x01\n" +
	"\x13MostProfitsProducts\x121\n" +
	"\x15year_month_created_at\x18\x01 \x01(\tR\x12yearMonthCreatedAt\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x05R\x06itemId\x12\x1d\n" +
	"\n" +
	"profit_sum\x18\x03 \x01(\x01R\tprofitSum\"O\n" +
	"\x18MostProfitsProductsBatch\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.protocol.MostProfitsProductsR\x05itemsB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_most_profits_products_proto_rawDescOnce sync.Once
	file_src_common_protocol_most_profits_products_proto_rawDescData []byte
)

func file_src_common_protocol_most_profits_products_proto_rawDescGZIP() []byte {
	file_src_common_protocol_most_profits_products_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_most_profits_products_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_most_profits_products_proto_rawDesc), len(file_src_common_protocol_most_profits_products_proto_rawDesc)))
	})
	return file_src_common_protocol_most_profits_products_proto_rawDescData
}

var file_src_common_protocol_most_profits_products_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_most_profits_products_proto_goTypes = []any{
	(*MostProfitsProducts)(nil),      // 0: protocol.MostProfitsProducts
	(*MostProfitsProductsBatch)(nil), // 1: protocol.MostProfitsProductsBatch
}
var file_src_common_protocol_most_profits_products_proto_depIdxs = []int32{
	0, // 0: protocol.MostProfitsProductsBatch.items:type_name -> protocol.MostProfitsProducts
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protocol_most_profits_products_proto_init() }
func file_src_common_protocol_most_profits_products_proto_init() {
	if File_src_common_protocol_most_profits_products_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_most_profits_products_proto_rawDesc), len(file_src_common_protocol_most_profits_products_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_most_profits_products_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_most_profits_products_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_most_profits_products_proto_msgTypes,
	}.Build()
	File_src_common_protocol_most_profits_products_proto = out.File
	file_src_common_protocol_most_profits_products_proto_goTypes = nil
	file_src_common_protocol_most_profits_products_proto_depIdxs = nil
}
