// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/most_purchases_user.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MostPurchasesUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreId       int32                  `protobuf:"varint,1,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UserId        int32                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PurchasesQty  int32                  `protobuf:"varint,3,opt,name=purchases_qty,json=purchasesQty,proto3" json:"purchases_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostPurchasesUser) Reset() {
	*x = MostPurchasesUser{}
	mi := &file_src_common_protocol_most_purchases_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostPurchasesUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostPurchasesUser) ProtoMessage() {}

func (x *MostPurchasesUser) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_most_purchases_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostPurchasesUser.ProtoReflect.Descriptor instead.
func (*MostPurchasesUser) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_most_purchases_user_proto_rawDescGZIP(), []int{0}
}

func (x *MostPurchasesUser) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *MostPurchasesUser) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MostPurchasesUser) GetPurchasesQty() int32 {
	if x != nil {
		return x.PurchasesQty
	}
	return 0
}

type MostPurchasesUserBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*MostPurchasesUser   `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MostPurchasesUserBatch) Reset() {
	*x = MostPurchasesUserBatch{}
	mi := &file_src_common_protocol_most_purchases_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MostPurchasesUserBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MostPurchasesUserBatch) ProtoMessage() {}

func (x *MostPurchasesUserBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_most_purchases_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MostPurchasesUserBatch.ProtoReflect.Descriptor instead.
func (*MostPurchasesUserBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_most_purchases_user_proto_rawDescGZIP(), []int{1}
}

func (x *MostPurchasesUserBatch) GetUsers() []*MostPurchasesUser {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_src_common_protocol_most_purchases_user_proto protoreflect.FileDescriptor

const file_src_common_protocol_most_purchases_user_proto_rawDesc = "" +
	"\n" +
	"-src/common/protocol/most_purchases_user.proto\x12\bprotocol\"l\n" +
	"\x11MostPurchasesUser\x12\x19\n" +
	"\bstore_id\x18\x01 \x01(\x05R\astoreId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x05R\x06userId\x12#\n" +
	"\rpurchases_qty\x18\x03 \x01(\x05R\fpurchasesQty\"K\n" +
	"\x16MostPurchasesUserBatch\x121\n" +
	"\x05users\x18\x01 \x03(\v2\x1b.protocol.MostPurchasesUserR\x05usersB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_most_purchases_user_proto_rawDescOnce sync.Once
	file_src_common_protocol_most_purchases_user_proto_rawDescData []byte
)

func file_src_common_protocol_most_purchases_user_proto_rawDescGZIP() []byte {
	file_src_common_protocol_most_purchases_user_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_most_purchases_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_most_purchases_user_proto_rawDesc), len(file_src_common_protocol_most_purchases_user_proto_rawDesc)))
	})
	return file_src_common_protocol_most_purchases_user_proto_rawDescData
}

var file_src_common_protocol_most_purchases_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_most_purchases_user_proto_goTypes = []any{
	(*MostPurchasesUser)(nil),      // 0: protocol.MostPurchasesUser
	(*MostPurchasesUserBatch)(nil), // 1: protocol.MostPurchasesUserBatch
}
var file_src_common_protocol_most_purchases_user_proto_depIdxs = []int32{
	0, // 0: protocol.MostPurchasesUserBatch.users:type_name -> protocol.MostPurchasesUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protocol_most_purchases_user_proto_init() }
func file_src_common_protocol_most_purchases_user_proto_init() {
	if File_src_common_protocol_most_purchases_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_most_purchases_user_proto_rawDesc), len(file_src_common_protocol_most_purchases_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_most_purchases_user_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_most_purchases_user_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_most_purchases_user_proto_msgTypes,
	}.Build()
	File_src_common_protocol_most_purchases_user_proto = out.File
	file_src_common_protocol_most_purchases_user_proto_goTypes = nil
	file_src_common_protocol_most_purchases_user_proto_depIdxs = nil
}
