// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: src/common/protocol/store.proto

package protocol

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreID       int32                  `protobuf:"varint,1,opt,name=StoreID,proto3" json:"StoreID,omitempty"`
	StoreName     string                 `protobuf:"bytes,2,opt,name=StoreName,proto3" json:"StoreName,omitempty"`
	Street        string                 `protobuf:"bytes,3,opt,name=Street,proto3" json:"Street,omitempty"`
	PostalCode    int32                  `protobuf:"varint,4,opt,name=PostalCode,proto3" json:"PostalCode,omitempty"`
	City          string                 `protobuf:"bytes,5,opt,name=City,proto3" json:"City,omitempty"`
	State         string                 `protobuf:"bytes,6,opt,name=State,proto3" json:"State,omitempty"`
	Latitude      float64                `protobuf:"fixed64,7,opt,name=Latitude,proto3" json:"Latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,8,opt,name=Longitude,proto3" json:"Longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_src_common_protocol_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_store_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetStoreID() int32 {
	if x != nil {
		return x.StoreID
	}
	return 0
}

func (x *Store) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *Store) GetStreet() string {
	if x != nil {
		return x.Street
	}
	return ""
}

func (x *Store) GetPostalCode() int32 {
	if x != nil {
		return x.PostalCode
	}
	return 0
}

func (x *Store) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Store) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Store) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Store) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

var File_src_common_protocol_store_proto protoreflect.FileDescriptor

const file_src_common_protocol_store_proto_rawDesc = "" +
	"\n" +
	"\x1fsrc/common/protocol/store.proto\x12\bprotocol\"\xdb\x01\n" +
	"\x05Store\x12\x18\n" +
	"\aStoreID\x18\x01 \x01(\x05R\aStoreID\x12\x1c\n" +
	"\tStoreName\x18\x02 \x01(\tR\tStoreName\x12\x16\n" +
	"\x06Street\x18\x03 \x01(\tR\x06Street\x12\x1e\n" +
	"\n" +
	"PostalCode\x18\x04 \x01(\x05R\n" +
	"PostalCode\x12\x12\n" +
	"\x04City\x18\x05 \x01(\tR\x04City\x12\x14\n" +
	"\x05State\x18\x06 \x01(\tR\x05State\x12\x1a\n" +
	"\bLatitude\x18\a \x01(\x01R\bLatitude\x12\x1c\n" +
	"\tLongitude\x18\b \x01(\x01R\tLongitudeB\x1eZ\x1csrc/joiner/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_store_proto_rawDescOnce sync.Once
	file_src_common_protocol_store_proto_rawDescData []byte
)

func file_src_common_protocol_store_proto_rawDescGZIP() []byte {
	file_src_common_protocol_store_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_store_proto_rawDesc), len(file_src_common_protocol_store_proto_rawDesc)))
	})
	return file_src_common_protocol_store_proto_rawDescData
}

var file_src_common_protocol_store_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_common_protocol_store_proto_goTypes = []any{
	(*Store)(nil), // 0: protocol.Store
}
var file_src_common_protocol_store_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_common_protocol_store_proto_init() }
func file_src_common_protocol_store_proto_init() {
	if File_src_common_protocol_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_store_proto_rawDesc), len(file_src_common_protocol_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_store_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_store_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_store_proto_msgTypes,
	}.Build()
	File_src_common_protocol_store_proto = out.File
	file_src_common_protocol_store_proto_goTypes = nil
	file_src_common_protocol_store_proto_depIdxs = nil
}
