// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/store_tpv.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StoreTPV struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	YearHalfCreatedAt string                 `protobuf:"bytes,1,opt,name=year_half_created_at,json=yearHalfCreatedAt,proto3" json:"year_half_created_at,omitempty"`
	StoreId           int32                  `protobuf:"varint,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	Tpv               int64                  `protobuf:"varint,3,opt,name=tpv,proto3" json:"tpv,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StoreTPV) Reset() {
	*x = StoreTPV{}
	mi := &file_src_common_protocol_store_tpv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreTPV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreTPV) ProtoMessage() {}

func (x *StoreTPV) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_store_tpv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreTPV.ProtoReflect.Descriptor instead.
func (*StoreTPV) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_store_tpv_proto_rawDescGZIP(), []int{0}
}

func (x *StoreTPV) GetYearHalfCreatedAt() string {
	if x != nil {
		return x.YearHalfCreatedAt
	}
	return ""
}

func (x *StoreTPV) GetStoreId() int32 {
	if x != nil {
		return x.StoreId
	}
	return 0
}

func (x *StoreTPV) GetTpv() int64 {
	if x != nil {
		return x.Tpv
	}
	return 0
}

type StoresTPV struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*StoreTPV            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoresTPV) Reset() {
	*x = StoresTPV{}
	mi := &file_src_common_protocol_store_tpv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoresTPV) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoresTPV) ProtoMessage() {}

func (x *StoresTPV) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_store_tpv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoresTPV.ProtoReflect.Descriptor instead.
func (*StoresTPV) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_store_tpv_proto_rawDescGZIP(), []int{1}
}

func (x *StoresTPV) GetItems() []*StoreTPV {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_src_common_protocol_store_tpv_proto protoreflect.FileDescriptor

const file_src_common_protocol_store_tpv_proto_rawDesc = "" +
	"\n" +
	"#src/common/protocol/store_tpv.proto\x12\bprotocol\"h\n" +
	"\bStoreTPV\x12/\n" +
	"\x14year_half_created_at\x18\x01 \x01(\tR\x11yearHalfCreatedAt\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\x05R\astoreId\x12\x10\n" +
	"\x03tpv\x18\x03 \x01(\x03R\x03tpv\"5\n" +
	"\tStoresTPV\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.protocol.StoreTPVR\x05itemsB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_store_tpv_proto_rawDescOnce sync.Once
	file_src_common_protocol_store_tpv_proto_rawDescData []byte
)

func file_src_common_protocol_store_tpv_proto_rawDescGZIP() []byte {
	file_src_common_protocol_store_tpv_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_store_tpv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_store_tpv_proto_rawDesc), len(file_src_common_protocol_store_tpv_proto_rawDesc)))
	})
	return file_src_common_protocol_store_tpv_proto_rawDescData
}

var file_src_common_protocol_store_tpv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_store_tpv_proto_goTypes = []any{
	(*StoreTPV)(nil),  // 0: protocol.StoreTPV
	(*StoresTPV)(nil), // 1: protocol.StoresTPV
}
var file_src_common_protocol_store_tpv_proto_depIdxs = []int32{
	0, // 0: protocol.StoresTPV.items:type_name -> protocol.StoreTPV
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protocol_store_tpv_proto_init() }
func file_src_common_protocol_store_tpv_proto_init() {
	if File_src_common_protocol_store_tpv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_store_tpv_proto_rawDesc), len(file_src_common_protocol_store_tpv_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_store_tpv_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_store_tpv_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_store_tpv_proto_msgTypes,
	}.Build()
	File_src_common_protocol_store_tpv_proto = out.File
	file_src_common_protocol_store_tpv_proto_goTypes = nil
	file_src_common_protocol_store_tpv_proto_depIdxs = nil
}
