// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: src/common/protocol/user.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gender        string                 `protobuf:"bytes,2,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthdate     string                 `protobuf:"bytes,3,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
	RegisteredAt  string                 `protobuf:"bytes,4,opt,name=registered_at,json=registeredAt,proto3" json:"registered_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_src_common_protocol_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_user_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *User) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *User) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

func (x *User) GetRegisteredAt() string {
	if x != nil {
		return x.RegisteredAt
	}
	return ""
}

type Users struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Users) Reset() {
	*x = Users{}
	mi := &file_src_common_protocol_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Users) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Users) ProtoMessage() {}

func (x *Users) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protocol_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Users.ProtoReflect.Descriptor instead.
func (*Users) Descriptor() ([]byte, []int) {
	return file_src_common_protocol_user_proto_rawDescGZIP(), []int{1}
}

func (x *Users) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_src_common_protocol_user_proto protoreflect.FileDescriptor

const file_src_common_protocol_user_proto_rawDesc = "" +
	"\n" +
	"\x1esrc/common/protocol/user.proto\x12\bprotocol\"z\n" +
	"\x04User\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x16\n" +
	"\x06gender\x18\x02 \x01(\tR\x06gender\x12\x1c\n" +
	"\tbirthdate\x18\x03 \x01(\tR\tbirthdate\x12#\n" +
	"\rregistered_at\x18\x04 \x01(\tR\fregisteredAt\"-\n" +
	"\x05Users\x12$\n" +
	"\x05users\x18\x01 \x03(\v2\x0e.protocol.UserR\x05usersB\x1eZ\x1csrc/common/protocol;protocolb\x06proto3"

var (
	file_src_common_protocol_user_proto_rawDescOnce sync.Once
	file_src_common_protocol_user_proto_rawDescData []byte
)

func file_src_common_protocol_user_proto_rawDescGZIP() []byte {
	file_src_common_protocol_user_proto_rawDescOnce.Do(func() {
		file_src_common_protocol_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protocol_user_proto_rawDesc), len(file_src_common_protocol_user_proto_rawDesc)))
	})
	return file_src_common_protocol_user_proto_rawDescData
}

var file_src_common_protocol_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protocol_user_proto_goTypes = []any{
	(*User)(nil),  // 0: protocol.User
	(*Users)(nil), // 1: protocol.Users
}
var file_src_common_protocol_user_proto_depIdxs = []int32{
	0, // 0: protocol.Users.users:type_name -> protocol.User
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protocol_user_proto_init() }
func file_src_common_protocol_user_proto_init() {
	if File_src_common_protocol_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protocol_user_proto_rawDesc), len(file_src_common_protocol_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protocol_user_proto_goTypes,
		DependencyIndexes: file_src_common_protocol_user_proto_depIdxs,
		MessageInfos:      file_src_common_protocol_user_proto_msgTypes,
	}.Build()
	File_src_common_protocol_user_proto = out.File
	file_src_common_protocol_user_proto_goTypes = nil
	file_src_common_protocol_user_proto_depIdxs = nil
}
