// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protocol/data_envelope.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DataEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	TaskType      int32                  `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	IsDone        bool                   `protobuf:"varint,3,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	IsRef         bool                   `protobuf:"varint,4,opt,name=is_ref,json=isRef,proto3" json:"is_ref,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	IsItems       bool                   `protobuf:"varint,6,opt,name=is_items,json=isItems,proto3" json:"is_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataEnvelope) Reset() {
	*x = DataEnvelope{}
	mi := &file_protocol_data_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataEnvelope) ProtoMessage() {}

func (x *DataEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_data_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataEnvelope.ProtoReflect.Descriptor instead.
func (*DataEnvelope) Descriptor() ([]byte, []int) {
	return file_protocol_data_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *DataEnvelope) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *DataEnvelope) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *DataEnvelope) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

func (x *DataEnvelope) GetIsRef() bool {
	if x != nil {
		return x.IsRef
	}
	return false
}

func (x *DataEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DataEnvelope) GetIsItems() bool {
	if x != nil {
		return x.IsItems
	}
	return false
}

var File_protocol_data_envelope_proto protoreflect.FileDescriptor

const file_protocol_data_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1cprotocol/data_envelope.proto\x12\bprotocol\"\xad\x01\n" +
	"\fDataEnvelope\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\x05R\btaskType\x12\x17\n" +
	"\ais_done\x18\x03 \x01(\bR\x06isDone\x12\x15\n" +
	"\x06is_ref\x18\x04 \x01(\bR\x05isRef\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12\x19\n" +
	"\bis_items\x18\x06 \x01(\bR\aisItemsB\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_protocol_data_envelope_proto_rawDescOnce sync.Once
	file_protocol_data_envelope_proto_rawDescData []byte
)

func file_protocol_data_envelope_proto_rawDescGZIP() []byte {
	file_protocol_data_envelope_proto_rawDescOnce.Do(func() {
		file_protocol_data_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_data_envelope_proto_rawDesc), len(file_protocol_data_envelope_proto_rawDesc)))
	})
	return file_protocol_data_envelope_proto_rawDescData
}

var file_protocol_data_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_data_envelope_proto_goTypes = []any{
	(*DataEnvelope)(nil), // 0: protocol.DataEnvelope
}
var file_protocol_data_envelope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_data_envelope_proto_init() }
func file_protocol_data_envelope_proto_init() {
	if File_protocol_data_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_data_envelope_proto_rawDesc), len(file_protocol_data_envelope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_data_envelope_proto_goTypes,
		DependencyIndexes: file_protocol_data_envelope_proto_depIdxs,
		MessageInfos:      file_protocol_data_envelope_proto_msgTypes,
	}.Build()
	File_protocol_data_envelope_proto = out.File
	file_protocol_data_envelope_proto_goTypes = nil
	file_protocol_data_envelope_proto_depIdxs = nil
}
