// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protocol/heartbeat.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeartBeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartBeat) Reset() {
	*x = HeartBeat{}
	mi := &file_protocol_heartbeat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartBeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartBeat) ProtoMessage() {}

func (x *HeartBeat) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_heartbeat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartBeat.ProtoReflect.Descriptor instead.
func (*HeartBeat) Descriptor() ([]byte, []int) {
	return file_protocol_heartbeat_proto_rawDescGZIP(), []int{0}
}

func (x *HeartBeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_protocol_heartbeat_proto protoreflect.FileDescriptor

const file_protocol_heartbeat_proto_rawDesc = "" +
	"\n" +
	"\x18protocol/heartbeat.proto\x12\bprotocol\")\n" +
	"\tHeartBeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestampB\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_protocol_heartbeat_proto_rawDescOnce sync.Once
	file_protocol_heartbeat_proto_rawDescData []byte
)

func file_protocol_heartbeat_proto_rawDescGZIP() []byte {
	file_protocol_heartbeat_proto_rawDescOnce.Do(func() {
		file_protocol_heartbeat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_heartbeat_proto_rawDesc), len(file_protocol_heartbeat_proto_rawDesc)))
	})
	return file_protocol_heartbeat_proto_rawDescData
}

var file_protocol_heartbeat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_heartbeat_proto_goTypes = []any{
	(*HeartBeat)(nil), // 0: protocol.HeartBeat
}
var file_protocol_heartbeat_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_heartbeat_proto_init() }
func file_protocol_heartbeat_proto_init() {
	if File_protocol_heartbeat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_heartbeat_proto_rawDesc), len(file_protocol_heartbeat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_heartbeat_proto_goTypes,
		DependencyIndexes: file_protocol_heartbeat_proto_depIdxs,
		MessageInfos:      file_protocol_heartbeat_proto_msgTypes,
	}.Build()
	File_protocol_heartbeat_proto = out.File
	file_protocol_heartbeat_proto_goTypes = nil
	file_protocol_heartbeat_proto_depIdxs = nil
}
