// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: protocol/message_counter.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageCounter struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ClientId       string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	AmountSent     int32                  `protobuf:"varint,2,opt,name=amount_sent,json=amountSent,proto3" json:"amount_sent,omitempty"`
	From           string                 `protobuf:"bytes,3,opt,name=from,proto3" json:"from,omitempty"`
	Next           string                 `protobuf:"bytes,4,opt,name=next,proto3" json:"next,omitempty"`
	SequenceNumber int32                  `protobuf:"varint,6,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Payload        []byte                 `protobuf:"bytes,7,opt,name=payload,proto3" json:"payload,omitempty"`
	TaskType       int32                  `protobuf:"varint,8,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageCounter) Reset() {
	*x = MessageCounter{}
	mi := &file_protocol_message_counter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageCounter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageCounter) ProtoMessage() {}

func (x *MessageCounter) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_message_counter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageCounter.ProtoReflect.Descriptor instead.
func (*MessageCounter) Descriptor() ([]byte, []int) {
	return file_protocol_message_counter_proto_rawDescGZIP(), []int{0}
}

func (x *MessageCounter) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *MessageCounter) GetAmountSent() int32 {
	if x != nil {
		return x.AmountSent
	}
	return 0
}

func (x *MessageCounter) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageCounter) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *MessageCounter) GetSequenceNumber() int32 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageCounter) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MessageCounter) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

var File_protocol_message_counter_proto protoreflect.FileDescriptor

const file_protocol_message_counter_proto_rawDesc = "" +
	"\n" +
	"\x1eprotocol/message_counter.proto\x12\bprotocol\"\xd6\x01\n" +
	"\x0eMessageCounter\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x1f\n" +
	"\vamount_sent\x18\x02 \x01(\x05R\n" +
	"amountSent\x12\x12\n" +
	"\x04from\x18\x03 \x01(\tR\x04from\x12\x12\n" +
	"\x04next\x18\x04 \x01(\tR\x04next\x12'\n" +
	"\x0fsequence_number\x18\x06 \x01(\x05R\x0esequenceNumber\x12\x18\n" +
	"\apayload\x18\a \x01(\fR\apayload\x12\x1b\n" +
	"\ttask_type\x18\b \x01(\x05R\btaskTypeB\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_protocol_message_counter_proto_rawDescOnce sync.Once
	file_protocol_message_counter_proto_rawDescData []byte
)

func file_protocol_message_counter_proto_rawDescGZIP() []byte {
	file_protocol_message_counter_proto_rawDescOnce.Do(func() {
		file_protocol_message_counter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_message_counter_proto_rawDesc), len(file_protocol_message_counter_proto_rawDesc)))
	})
	return file_protocol_message_counter_proto_rawDescData
}

var file_protocol_message_counter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_message_counter_proto_goTypes = []any{
	(*MessageCounter)(nil), // 0: protocol.MessageCounter
}
var file_protocol_message_counter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_message_counter_proto_init() }
func file_protocol_message_counter_proto_init() {
	if File_protocol_message_counter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_message_counter_proto_rawDesc), len(file_protocol_message_counter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_message_counter_proto_goTypes,
		DependencyIndexes: file_protocol_message_counter_proto_depIdxs,
		MessageInfos:      file_protocol_message_counter_proto_msgTypes,
	}.Build()
	File_protocol_message_counter_proto = out.File
	file_protocol_message_counter_proto_goTypes = nil
	file_protocol_message_counter_proto_depIdxs = nil
}
