// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protocol/reference_envolope.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferenceEnvolope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceType int32                  `protobuf:"varint,1,opt,name=reference_type,json=referenceType,proto3" json:"reference_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	IsDone        bool                   `protobuf:"varint,3,opt,name=is_done,json=isDone,proto3" json:"is_done,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceEnvolope) Reset() {
	*x = ReferenceEnvolope{}
	mi := &file_protocol_reference_envolope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceEnvolope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceEnvolope) ProtoMessage() {}

func (x *ReferenceEnvolope) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_reference_envolope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceEnvolope.ProtoReflect.Descriptor instead.
func (*ReferenceEnvolope) Descriptor() ([]byte, []int) {
	return file_protocol_reference_envolope_proto_rawDescGZIP(), []int{0}
}

func (x *ReferenceEnvolope) GetReferenceType() int32 {
	if x != nil {
		return x.ReferenceType
	}
	return 0
}

func (x *ReferenceEnvolope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ReferenceEnvolope) GetIsDone() bool {
	if x != nil {
		return x.IsDone
	}
	return false
}

var File_protocol_reference_envolope_proto protoreflect.FileDescriptor

const file_protocol_reference_envolope_proto_rawDesc = "" +
	"\n" +
	"!protocol/reference_envolope.proto\x12\bprotocol\"m\n" +
	"\x11ReferenceEnvolope\x12%\n" +
	"\x0ereference_type\x18\x01 \x01(\x05R\rreferenceType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x17\n" +
	"\ais_done\x18\x03 \x01(\bR\x06isDoneB\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_protocol_reference_envolope_proto_rawDescOnce sync.Once
	file_protocol_reference_envolope_proto_rawDescData []byte
)

func file_protocol_reference_envolope_proto_rawDescGZIP() []byte {
	file_protocol_reference_envolope_proto_rawDescOnce.Do(func() {
		file_protocol_reference_envolope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_reference_envolope_proto_rawDesc), len(file_protocol_reference_envolope_proto_rawDesc)))
	})
	return file_protocol_reference_envolope_proto_rawDescData
}

var file_protocol_reference_envolope_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_reference_envolope_proto_goTypes = []any{
	(*ReferenceEnvolope)(nil), // 0: protocol.ReferenceEnvolope
}
var file_protocol_reference_envolope_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_reference_envolope_proto_init() }
func file_protocol_reference_envolope_proto_init() {
	if File_protocol_reference_envolope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_reference_envolope_proto_rawDesc), len(file_protocol_reference_envolope_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_reference_envolope_proto_goTypes,
		DependencyIndexes: file_protocol_reference_envolope_proto_depIdxs,
		MessageInfos:      file_protocol_reference_envolope_proto_msgTypes,
	}.Build()
	File_protocol_reference_envolope_proto = out.File
	file_protocol_reference_envolope_proto_goTypes = nil
	file_protocol_reference_envolope_proto_depIdxs = nil
}
