// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: protocol/sync_message.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	LeaderId      int32                  `protobuf:"varint,2,opt,name=leader_id,json=leaderId,proto3" json:"leader_id,omitempty"`
	Action        int32                  `protobuf:"varint,3,opt,name=action,proto3" json:"action,omitempty"`
	RoundId       string                 `protobuf:"bytes,4,opt,name=round_id,json=roundId,proto3" json:"round_id,omitempty"`
	Envelope      []byte                 `protobuf:"bytes,5,opt,name=envelope,proto3" json:"envelope,omitempty"` // optional
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncMessage) Reset() {
	*x = SyncMessage{}
	mi := &file_protocol_sync_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMessage) ProtoMessage() {}

func (x *SyncMessage) ProtoReflect() protoreflect.Message {
	mi := &file_protocol_sync_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMessage.ProtoReflect.Descriptor instead.
func (*SyncMessage) Descriptor() ([]byte, []int) {
	return file_protocol_sync_message_proto_rawDescGZIP(), []int{0}
}

func (x *SyncMessage) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *SyncMessage) GetLeaderId() int32 {
	if x != nil {
		return x.LeaderId
	}
	return 0
}

func (x *SyncMessage) GetAction() int32 {
	if x != nil {
		return x.Action
	}
	return 0
}

func (x *SyncMessage) GetRoundId() string {
	if x != nil {
		return x.RoundId
	}
	return ""
}

func (x *SyncMessage) GetEnvelope() []byte {
	if x != nil {
		return x.Envelope
	}
	return nil
}

var File_protocol_sync_message_proto protoreflect.FileDescriptor

const file_protocol_sync_message_proto_rawDesc = "" +
	"\n" +
	"\x1bprotocol/sync_message.proto\x12\bprotocol\"\x92\x01\n" +
	"\vSyncMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\x12\x1b\n" +
	"\tleader_id\x18\x02 \x01(\x05R\bleaderId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\x05R\x06action\x12\x19\n" +
	"\bround_id\x18\x04 \x01(\tR\aroundId\x12\x1a\n" +
	"\benvelope\x18\x05 \x01(\fR\benvelopeB\fZ\n" +
	"./protocolb\x06proto3"

var (
	file_protocol_sync_message_proto_rawDescOnce sync.Once
	file_protocol_sync_message_proto_rawDescData []byte
)

func file_protocol_sync_message_proto_rawDescGZIP() []byte {
	file_protocol_sync_message_proto_rawDescOnce.Do(func() {
		file_protocol_sync_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protocol_sync_message_proto_rawDesc), len(file_protocol_sync_message_proto_rawDesc)))
	})
	return file_protocol_sync_message_proto_rawDescData
}

var file_protocol_sync_message_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protocol_sync_message_proto_goTypes = []any{
	(*SyncMessage)(nil), // 0: protocol.SyncMessage
}
var file_protocol_sync_message_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protocol_sync_message_proto_init() }
func file_protocol_sync_message_proto_init() {
	if File_protocol_sync_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protocol_sync_message_proto_rawDesc), len(file_protocol_sync_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protocol_sync_message_proto_goTypes,
		DependencyIndexes: file_protocol_sync_message_proto_depIdxs,
		MessageInfos:      file_protocol_sync_message_proto_msgTypes,
	}.Build()
	File_protocol_sync_message_proto = out.File
	file_protocol_sync_message_proto_goTypes = nil
	file_protocol_sync_message_proto_depIdxs = nil
}
