// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.12.4
// source: src/joiner/protocol/reference_batch.proto

package protocol

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferenceBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DatasetType   int32                  `protobuf:"varint,1,opt,name=dataset_type,json=datasetType,proto3" json:"dataset_type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceBatch) Reset() {
	*x = ReferenceBatch{}
	mi := &file_src_joiner_protocol_reference_batch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceBatch) ProtoMessage() {}

func (x *ReferenceBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_joiner_protocol_reference_batch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceBatch.ProtoReflect.Descriptor instead.
func (*ReferenceBatch) Descriptor() ([]byte, []int) {
	return file_src_joiner_protocol_reference_batch_proto_rawDescGZIP(), []int{0}
}

func (x *ReferenceBatch) GetDatasetType() int32 {
	if x != nil {
		return x.DatasetType
	}
	return 0
}

func (x *ReferenceBatch) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_src_joiner_protocol_reference_batch_proto protoreflect.FileDescriptor

const file_src_joiner_protocol_reference_batch_proto_rawDesc = "" +
	"\n" +
	")src/joiner/protocol/reference_batch.proto\x12\bprotocol\"M\n" +
	"\x0eReferenceBatch\x12!\n" +
	"\fdataset_type\x18\x01 \x01(\x05R\vdatasetType\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayloadB\x1eZ\x1csrc/joiner/protocol;protocolb\x06proto3"

var (
	file_src_joiner_protocol_reference_batch_proto_rawDescOnce sync.Once
	file_src_joiner_protocol_reference_batch_proto_rawDescData []byte
)

func file_src_joiner_protocol_reference_batch_proto_rawDescGZIP() []byte {
	file_src_joiner_protocol_reference_batch_proto_rawDescOnce.Do(func() {
		file_src_joiner_protocol_reference_batch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_joiner_protocol_reference_batch_proto_rawDesc), len(file_src_joiner_protocol_reference_batch_proto_rawDesc)))
	})
	return file_src_joiner_protocol_reference_batch_proto_rawDescData
}

var file_src_joiner_protocol_reference_batch_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_src_joiner_protocol_reference_batch_proto_goTypes = []any{
	(*ReferenceBatch)(nil), // 0: protocol.ReferenceBatch
}
var file_src_joiner_protocol_reference_batch_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_src_joiner_protocol_reference_batch_proto_init() }
func file_src_joiner_protocol_reference_batch_proto_init() {
	if File_src_joiner_protocol_reference_batch_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_joiner_protocol_reference_batch_proto_rawDesc), len(file_src_joiner_protocol_reference_batch_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_joiner_protocol_reference_batch_proto_goTypes,
		DependencyIndexes: file_src_joiner_protocol_reference_batch_proto_depIdxs,
		MessageInfos:      file_src_joiner_protocol_reference_batch_proto_msgTypes,
	}.Build()
	File_src_joiner_protocol_reference_batch_proto = out.File
	file_src_joiner_protocol_reference_batch_proto_goTypes = nil
	file_src_joiner_protocol_reference_batch_proto_depIdxs = nil
}
