# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/common/protobufs/protocol/leader_election.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3src/common/protobufs/protocol/leader_election.proto\x12\x08protocol\"2\n\x0eLeaderElection\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0cmessage_type\x18\x02 \x01(\x05\x42\x0cZ\n./protocolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.common.protobufs.protocol.leader_election_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./protocol'
  _LEADERELECTION._serialized_start=65
  _LEADERELECTION._serialized_end=115
# @@protoc_insertion_point(module_scope)
