// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: src/common/protobufs/transaction_items.proto

package transaction_items

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionItems struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ItemId        int64                  `protobuf:"varint,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	UnitPrice     float64                `protobuf:"fixed64,4,opt,name=unit_price,json=unitPrice,proto3" json:"unit_price,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,5,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionItems) Reset() {
	*x = TransactionItems{}
	mi := &file_src_common_protobufs_transaction_items_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItems) ProtoMessage() {}

func (x *TransactionItems) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protobufs_transaction_items_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItems.ProtoReflect.Descriptor instead.
func (*TransactionItems) Descriptor() ([]byte, []int) {
	return file_src_common_protobufs_transaction_items_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionItems) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *TransactionItems) GetItemId() int64 {
	if x != nil {
		return x.ItemId
	}
	return 0
}

func (x *TransactionItems) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TransactionItems) GetUnitPrice() float64 {
	if x != nil {
		return x.UnitPrice
	}
	return 0
}

func (x *TransactionItems) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *TransactionItems) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TransactionItemsBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskType         int32                  `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	TransactionItems []*TransactionItems    `protobuf:"bytes,2,rep,name=transaction_items,json=transactionItems,proto3" json:"transaction_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionItemsBatch) Reset() {
	*x = TransactionItemsBatch{}
	mi := &file_src_common_protobufs_transaction_items_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItemsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItemsBatch) ProtoMessage() {}

func (x *TransactionItemsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_src_common_protobufs_transaction_items_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItemsBatch.ProtoReflect.Descriptor instead.
func (*TransactionItemsBatch) Descriptor() ([]byte, []int) {
	return file_src_common_protobufs_transaction_items_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionItemsBatch) GetTaskType() int32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *TransactionItemsBatch) GetTransactionItems() []*TransactionItems {
	if x != nil {
		return x.TransactionItems
	}
	return nil
}

var File_src_common_protobufs_transaction_items_proto protoreflect.FileDescriptor

const file_src_common_protobufs_transaction_items_proto_rawDesc = "" +
	"\n" +
	",src/common/protobufs/transaction_items.proto\"\xc8\x01\n" +
	"\x10TransactionItems\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\x03R\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12\x1d\n" +
	"\n" +
	"unit_price\x18\x04 \x01(\x01R\tunitPrice\x12\x1a\n" +
	"\bsubtotal\x18\x05 \x01(\x01R\bsubtotal\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"t\n" +
	"\x15TransactionItemsBatch\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\x05R\btaskType\x12>\n" +
	"\x11transaction_items\x18\x02 \x03(\v2\x11.TransactionItemsR\x10transactionItemsB\x15Z\x13./transaction_itemsb\x06proto3"

var (
	file_src_common_protobufs_transaction_items_proto_rawDescOnce sync.Once
	file_src_common_protobufs_transaction_items_proto_rawDescData []byte
)

func file_src_common_protobufs_transaction_items_proto_rawDescGZIP() []byte {
	file_src_common_protobufs_transaction_items_proto_rawDescOnce.Do(func() {
		file_src_common_protobufs_transaction_items_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_src_common_protobufs_transaction_items_proto_rawDesc), len(file_src_common_protobufs_transaction_items_proto_rawDesc)))
	})
	return file_src_common_protobufs_transaction_items_proto_rawDescData
}

var file_src_common_protobufs_transaction_items_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_src_common_protobufs_transaction_items_proto_goTypes = []any{
	(*TransactionItems)(nil),      // 0: TransactionItems
	(*TransactionItemsBatch)(nil), // 1: TransactionItemsBatch
}
var file_src_common_protobufs_transaction_items_proto_depIdxs = []int32{
	0, // 0: TransactionItemsBatch.transaction_items:type_name -> TransactionItems
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_src_common_protobufs_transaction_items_proto_init() }
func file_src_common_protobufs_transaction_items_proto_init() {
	if File_src_common_protobufs_transaction_items_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_src_common_protobufs_transaction_items_proto_rawDesc), len(file_src_common_protobufs_transaction_items_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_src_common_protobufs_transaction_items_proto_goTypes,
		DependencyIndexes: file_src_common_protobufs_transaction_items_proto_depIdxs,
		MessageInfos:      file_src_common_protobufs_transaction_items_proto_msgTypes,
	}.Build()
	File_src_common_protobufs_transaction_items_proto = out.File
	file_src_common_protobufs_transaction_items_proto_goTypes = nil
	file_src_common_protobufs_transaction_items_proto_depIdxs = nil
}
