// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v5.29.0
// source: raw/menu_item.proto

package raw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_raw_menu_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_raw_menu_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_raw_menu_item_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *MenuItem) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type MenuItemsBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MenuItems     []*MenuItem            `protobuf:"bytes,1,rep,name=menu_items,json=menuItems,proto3" json:"menu_items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItemsBatch) Reset() {
	*x = MenuItemsBatch{}
	mi := &file_raw_menu_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItemsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItemsBatch) ProtoMessage() {}

func (x *MenuItemsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_raw_menu_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItemsBatch.ProtoReflect.Descriptor instead.
func (*MenuItemsBatch) Descriptor() ([]byte, []int) {
	return file_raw_menu_item_proto_rawDescGZIP(), []int{1}
}

func (x *MenuItemsBatch) GetMenuItems() []*MenuItem {
	if x != nil {
		return x.MenuItems
	}
	return nil
}

var File_raw_menu_item_proto protoreflect.FileDescriptor

const file_raw_menu_item_proto_rawDesc = "" +
	"\n" +
	"\x13raw/menu_item.proto\x12\x03raw\"@\n" +
	"\bMenuItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\">\n" +
	"\x0eMenuItemsBatch\x12,\n" +
	"\n" +
	"menu_items\x18\x01 \x03(\v2\r.raw.MenuItemR\tmenuItemsB\aZ\x05./rawb\x06proto3"

var (
	file_raw_menu_item_proto_rawDescOnce sync.Once
	file_raw_menu_item_proto_rawDescData []byte
)

func file_raw_menu_item_proto_rawDescGZIP() []byte {
	file_raw_menu_item_proto_rawDescOnce.Do(func() {
		file_raw_menu_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_menu_item_proto_rawDesc), len(file_raw_menu_item_proto_rawDesc)))
	})
	return file_raw_menu_item_proto_rawDescData
}

var file_raw_menu_item_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raw_menu_item_proto_goTypes = []any{
	(*MenuItem)(nil),       // 0: raw.MenuItem
	(*MenuItemsBatch)(nil), // 1: raw.MenuItemsBatch
}
var file_raw_menu_item_proto_depIdxs = []int32{
	0, // 0: raw.MenuItemsBatch.menu_items:type_name -> raw.MenuItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raw_menu_item_proto_init() }
func file_raw_menu_item_proto_init() {
	if File_raw_menu_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_menu_item_proto_rawDesc), len(file_raw_menu_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raw_menu_item_proto_goTypes,
		DependencyIndexes: file_raw_menu_item_proto_depIdxs,
		MessageInfos:      file_raw_menu_item_proto_msgTypes,
	}.Build()
	File_raw_menu_item_proto = out.File
	file_raw_menu_item_proto_goTypes = nil
	file_raw_menu_item_proto_depIdxs = nil
}
