// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: raw/store.proto

package raw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Store struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemName      string                 `protobuf:"bytes,2,opt,name=item_name,json=itemName,proto3" json:"item_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_raw_store_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_raw_store_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Store.ProtoReflect.Descriptor instead.
func (*Store) Descriptor() ([]byte, []int) {
	return file_raw_store_proto_rawDescGZIP(), []int{0}
}

func (x *Store) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Store) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

type StoreBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stores        []*Store               `protobuf:"bytes,1,rep,name=stores,proto3" json:"stores,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreBatch) Reset() {
	*x = StoreBatch{}
	mi := &file_raw_store_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreBatch) ProtoMessage() {}

func (x *StoreBatch) ProtoReflect() protoreflect.Message {
	mi := &file_raw_store_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreBatch.ProtoReflect.Descriptor instead.
func (*StoreBatch) Descriptor() ([]byte, []int) {
	return file_raw_store_proto_rawDescGZIP(), []int{1}
}

func (x *StoreBatch) GetStores() []*Store {
	if x != nil {
		return x.Stores
	}
	return nil
}

var File_raw_store_proto protoreflect.FileDescriptor

const file_raw_store_proto_rawDesc = "" +
	"\n" +
	"\x0fraw/store.proto\x12\x03raw\"=\n" +
	"\x05Store\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1b\n" +
	"\titem_name\x18\x02 \x01(\tR\bitemName\"0\n" +
	"\n" +
	"StoreBatch\x12\"\n" +
	"\x06stores\x18\x01 \x03(\v2\n" +
	".raw.StoreR\x06storesB\aZ\x05./rawb\x06proto3"

var (
	file_raw_store_proto_rawDescOnce sync.Once
	file_raw_store_proto_rawDescData []byte
)

func file_raw_store_proto_rawDescGZIP() []byte {
	file_raw_store_proto_rawDescOnce.Do(func() {
		file_raw_store_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_store_proto_rawDesc), len(file_raw_store_proto_rawDesc)))
	})
	return file_raw_store_proto_rawDescData
}

var file_raw_store_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raw_store_proto_goTypes = []any{
	(*Store)(nil),      // 0: raw.Store
	(*StoreBatch)(nil), // 1: raw.StoreBatch
}
var file_raw_store_proto_depIdxs = []int32{
	0, // 0: raw.StoreBatch.stores:type_name -> raw.Store
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raw_store_proto_init() }
func file_raw_store_proto_init() {
	if File_raw_store_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_store_proto_rawDesc), len(file_raw_store_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raw_store_proto_goTypes,
		DependencyIndexes: file_raw_store_proto_depIdxs,
		MessageInfos:      file_raw_store_proto_msgTypes,
	}.Build()
	File_raw_store_proto = out.File
	file_raw_store_proto_goTypes = nil
	file_raw_store_proto_depIdxs = nil
}
