// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: raw/transaction.proto

package raw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FinalAmount   float64                `protobuf:"fixed64,4,opt,name=final_amount,json=finalAmount,proto3" json:"final_amount,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_raw_transaction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_raw_transaction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_raw_transaction_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Transaction) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *Transaction) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Transaction) GetFinalAmount() float64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

func (x *Transaction) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TransactionBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Transactions  []*Transaction         `protobuf:"bytes,1,rep,name=transactions,proto3" json:"transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionBatch) Reset() {
	*x = TransactionBatch{}
	mi := &file_raw_transaction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionBatch) ProtoMessage() {}

func (x *TransactionBatch) ProtoReflect() protoreflect.Message {
	mi := &file_raw_transaction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionBatch.ProtoReflect.Descriptor instead.
func (*TransactionBatch) Descriptor() ([]byte, []int) {
	return file_raw_transaction_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionBatch) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_raw_transaction_proto protoreflect.FileDescriptor

const file_raw_transaction_proto_rawDesc = "" +
	"\n" +
	"\x15raw/transaction.proto\x12\x03raw\"\xaa\x01\n" +
	"\vTransaction\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12!\n" +
	"\ffinal_amount\x18\x04 \x01(\x01R\vfinalAmount\x12\x1d\n" +
	"\n" +
	"created_at\x18\x05 \x01(\tR\tcreatedAt\"H\n" +
	"\x10TransactionBatch\x124\n" +
	"\ftransactions\x18\x01 \x03(\v2\x10.raw.TransactionR\ftransactionsB4Z2github.com/maxogod/distro-tp/src/common/models/rawb\x06proto3"

var (
	file_raw_transaction_proto_rawDescOnce sync.Once
	file_raw_transaction_proto_rawDescData []byte
)

func file_raw_transaction_proto_rawDescGZIP() []byte {
	file_raw_transaction_proto_rawDescOnce.Do(func() {
		file_raw_transaction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_transaction_proto_rawDesc), len(file_raw_transaction_proto_rawDesc)))
	})
	return file_raw_transaction_proto_rawDescData
}

var file_raw_transaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raw_transaction_proto_goTypes = []any{
	(*Transaction)(nil),      // 0: raw.Transaction
	(*TransactionBatch)(nil), // 1: raw.TransactionBatch
}
var file_raw_transaction_proto_depIdxs = []int32{
	0, // 0: raw.TransactionBatch.transactions:type_name -> raw.Transaction
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raw_transaction_proto_init() }
func file_raw_transaction_proto_init() {
	if File_raw_transaction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_transaction_proto_rawDesc), len(file_raw_transaction_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raw_transaction_proto_goTypes,
		DependencyIndexes: file_raw_transaction_proto_depIdxs,
		MessageInfos:      file_raw_transaction_proto_msgTypes,
	}.Build()
	File_raw_transaction_proto = out.File
	file_raw_transaction_proto_goTypes = nil
	file_raw_transaction_proto_depIdxs = nil
}
