// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: raw/transaction_item.proto

package raw

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,2,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Subtotal      float64                `protobuf:"fixed64,3,opt,name=subtotal,proto3" json:"subtotal,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionItem) Reset() {
	*x = TransactionItem{}
	mi := &file_raw_transaction_item_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItem) ProtoMessage() {}

func (x *TransactionItem) ProtoReflect() protoreflect.Message {
	mi := &file_raw_transaction_item_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItem.ProtoReflect.Descriptor instead.
func (*TransactionItem) Descriptor() ([]byte, []int) {
	return file_raw_transaction_item_proto_rawDescGZIP(), []int{0}
}

func (x *TransactionItem) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *TransactionItem) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *TransactionItem) GetSubtotal() float64 {
	if x != nil {
		return x.Subtotal
	}
	return 0
}

func (x *TransactionItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type TransactionItemsBatch struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TransactionItems []*TransactionItem     `protobuf:"bytes,1,rep,name=transaction_items,json=transactionItems,proto3" json:"transaction_items,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TransactionItemsBatch) Reset() {
	*x = TransactionItemsBatch{}
	mi := &file_raw_transaction_item_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionItemsBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionItemsBatch) ProtoMessage() {}

func (x *TransactionItemsBatch) ProtoReflect() protoreflect.Message {
	mi := &file_raw_transaction_item_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionItemsBatch.ProtoReflect.Descriptor instead.
func (*TransactionItemsBatch) Descriptor() ([]byte, []int) {
	return file_raw_transaction_item_proto_rawDescGZIP(), []int{1}
}

func (x *TransactionItemsBatch) GetTransactionItems() []*TransactionItem {
	if x != nil {
		return x.TransactionItems
	}
	return nil
}

var File_raw_transaction_item_proto protoreflect.FileDescriptor

const file_raw_transaction_item_proto_rawDesc = "" +
	"\n" +
	"\x1araw/transaction_item.proto\x12\x03raw\"\x81\x01\n" +
	"\x0fTransactionItem\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1a\n" +
	"\bquantity\x18\x02 \x01(\x05R\bquantity\x12\x1a\n" +
	"\bsubtotal\x18\x03 \x01(\x01R\bsubtotal\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\tR\tcreatedAt\"Z\n" +
	"\x15TransactionItemsBatch\x12A\n" +
	"\x11transaction_items\x18\x01 \x03(\v2\x14.raw.TransactionItemR\x10transactionItemsB4Z2github.com/maxogod/distro-tp/src/common/models/rawb\x06proto3"

var (
	file_raw_transaction_item_proto_rawDescOnce sync.Once
	file_raw_transaction_item_proto_rawDescData []byte
)

func file_raw_transaction_item_proto_rawDescGZIP() []byte {
	file_raw_transaction_item_proto_rawDescOnce.Do(func() {
		file_raw_transaction_item_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_raw_transaction_item_proto_rawDesc), len(file_raw_transaction_item_proto_rawDesc)))
	})
	return file_raw_transaction_item_proto_rawDescData
}

var file_raw_transaction_item_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_raw_transaction_item_proto_goTypes = []any{
	(*TransactionItem)(nil),       // 0: raw.TransactionItem
	(*TransactionItemsBatch)(nil), // 1: raw.TransactionItemsBatch
}
var file_raw_transaction_item_proto_depIdxs = []int32{
	0, // 0: raw.TransactionItemsBatch.transaction_items:type_name -> raw.TransactionItem
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_raw_transaction_item_proto_init() }
func file_raw_transaction_item_proto_init() {
	if File_raw_transaction_item_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_raw_transaction_item_proto_rawDesc), len(file_raw_transaction_item_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_raw_transaction_item_proto_goTypes,
		DependencyIndexes: file_raw_transaction_item_proto_depIdxs,
		MessageInfos:      file_raw_transaction_item_proto_msgTypes,
	}.Build()
	File_raw_transaction_item_proto = out.File
	file_raw_transaction_item_proto_goTypes = nil
	file_raw_transaction_item_proto_depIdxs = nil
}
