# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/common/protobufs/protocol/heartbeat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-src/common/protobufs/protocol/heartbeat.proto\x12\x08protocol\"\x1e\n\tHeartBeat\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x42\x0cZ\n./protocolb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.common.protobufs.protocol.heartbeat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\n./protocol'
  _HEARTBEAT._serialized_start=59
  _HEARTBEAT._serialized_end=89
# @@protoc_insertion_point(module_scope)
