// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: task_type.proto

package task_type

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskType struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskType      uint32                 `protobuf:"varint,1,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskType) Reset() {
	*x = TaskType{}
	mi := &file_task_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskType) ProtoMessage() {}

func (x *TaskType) ProtoReflect() protoreflect.Message {
	mi := &file_task_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskType.ProtoReflect.Descriptor instead.
func (*TaskType) Descriptor() ([]byte, []int) {
	return file_task_type_proto_rawDescGZIP(), []int{0}
}

func (x *TaskType) GetTaskType() uint32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

var File_task_type_proto protoreflect.FileDescriptor

const file_task_type_proto_rawDesc = "" +
	"\n" +
	"\x0ftask_type.proto\"'\n" +
	"\bTaskType\x12\x1b\n" +
	"\ttask_type\x18\x01 \x01(\rR\btaskTypeB\rZ\v./task_typeb\x06proto3"

var (
	file_task_type_proto_rawDescOnce sync.Once
	file_task_type_proto_rawDescData []byte
)

func file_task_type_proto_rawDescGZIP() []byte {
	file_task_type_proto_rawDescOnce.Do(func() {
		file_task_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_task_type_proto_rawDesc), len(file_task_type_proto_rawDesc)))
	})
	return file_task_type_proto_rawDescData
}

var file_task_type_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_task_type_proto_goTypes = []any{
	(*TaskType)(nil), // 0: TaskType
}
var file_task_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_task_type_proto_init() }
func file_task_type_proto_init() {
	if File_task_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_task_type_proto_rawDesc), len(file_task_type_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_task_type_proto_goTypes,
		DependencyIndexes: file_task_type_proto_depIdxs,
		MessageInfos:      file_task_type_proto_msgTypes,
	}.Build()
	File_task_type_proto = out.File
	file_task_type_proto_goTypes = nil
	file_task_type_proto_depIdxs = nil
}
