// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v3.21.12
// source: join_most_purchases_user.proto

package joined

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JoinMostPurchasesUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StoreName     string                 `protobuf:"bytes,1,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	UserBirthdate string                 `protobuf:"bytes,2,opt,name=user_birthdate,json=userBirthdate,proto3" json:"user_birthdate,omitempty"` // ej: "2011-06-26"
	PurchasesQty  int32                  `protobuf:"varint,3,opt,name=purchases_qty,json=purchasesQty,proto3" json:"purchases_qty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMostPurchasesUser) Reset() {
	*x = JoinMostPurchasesUser{}
	mi := &file_join_most_purchases_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMostPurchasesUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMostPurchasesUser) ProtoMessage() {}

func (x *JoinMostPurchasesUser) ProtoReflect() protoreflect.Message {
	mi := &file_join_most_purchases_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMostPurchasesUser.ProtoReflect.Descriptor instead.
func (*JoinMostPurchasesUser) Descriptor() ([]byte, []int) {
	return file_join_most_purchases_user_proto_rawDescGZIP(), []int{0}
}

func (x *JoinMostPurchasesUser) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *JoinMostPurchasesUser) GetUserBirthdate() string {
	if x != nil {
		return x.UserBirthdate
	}
	return ""
}

func (x *JoinMostPurchasesUser) GetPurchasesQty() int32 {
	if x != nil {
		return x.PurchasesQty
	}
	return 0
}

type JoinMostPurchasesUserBatch struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Users         []*JoinMostPurchasesUser `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinMostPurchasesUserBatch) Reset() {
	*x = JoinMostPurchasesUserBatch{}
	mi := &file_join_most_purchases_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinMostPurchasesUserBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinMostPurchasesUserBatch) ProtoMessage() {}

func (x *JoinMostPurchasesUserBatch) ProtoReflect() protoreflect.Message {
	mi := &file_join_most_purchases_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinMostPurchasesUserBatch.ProtoReflect.Descriptor instead.
func (*JoinMostPurchasesUserBatch) Descriptor() ([]byte, []int) {
	return file_join_most_purchases_user_proto_rawDescGZIP(), []int{1}
}

func (x *JoinMostPurchasesUserBatch) GetUsers() []*JoinMostPurchasesUser {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_join_most_purchases_user_proto protoreflect.FileDescriptor

const file_join_most_purchases_user_proto_rawDesc = "" +
	"\n" +
	"\x1ejoin_most_purchases_user.proto\x12\bprotocol\"\x82\x01\n" +
	"\x15JoinMostPurchasesUser\x12\x1d\n" +
	"\n" +
	"store_name\x18\x01 \x01(\tR\tstoreName\x12%\n" +
	"\x0euser_birthdate\x18\x02 \x01(\tR\ruserBirthdate\x12#\n" +
	"\rpurchases_qty\x18\x03 \x01(\x05R\fpurchasesQty\"S\n" +
	"\x1aJoinMostPurchasesUserBatch\x125\n" +
	"\x05users\x18\x01 \x03(\v2\x1f.protocol.JoinMostPurchasesUserR\x05usersB\x11Z\x0f./joined;joinedb\x06proto3"

var (
	file_join_most_purchases_user_proto_rawDescOnce sync.Once
	file_join_most_purchases_user_proto_rawDescData []byte
)

func file_join_most_purchases_user_proto_rawDescGZIP() []byte {
	file_join_most_purchases_user_proto_rawDescOnce.Do(func() {
		file_join_most_purchases_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_join_most_purchases_user_proto_rawDesc), len(file_join_most_purchases_user_proto_rawDesc)))
	})
	return file_join_most_purchases_user_proto_rawDescData
}

var file_join_most_purchases_user_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_join_most_purchases_user_proto_goTypes = []any{
	(*JoinMostPurchasesUser)(nil),      // 0: protocol.JoinMostPurchasesUser
	(*JoinMostPurchasesUserBatch)(nil), // 1: protocol.JoinMostPurchasesUserBatch
}
var file_join_most_purchases_user_proto_depIdxs = []int32{
	0, // 0: protocol.JoinMostPurchasesUserBatch.users:type_name -> protocol.JoinMostPurchasesUser
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_join_most_purchases_user_proto_init() }
func file_join_most_purchases_user_proto_init() {
	if File_join_most_purchases_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_join_most_purchases_user_proto_rawDesc), len(file_join_most_purchases_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_join_most_purchases_user_proto_goTypes,
		DependencyIndexes: file_join_most_purchases_user_proto_depIdxs,
		MessageInfos:      file_join_most_purchases_user_proto_msgTypes,
	}.Build()
	File_join_most_purchases_user_proto = out.File
	file_join_most_purchases_user_proto_goTypes = nil
	file_join_most_purchases_user_proto_depIdxs = nil
}
